import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {starter,sharedEdge,validateHouse} from '../web/model.js';
import {centerOf,entranceFor,roomRoute,walkingRoute,stepAlongPath,canExploreAt,canOccupy,findWalkingPath,roomAtPoint,houseBounds} from '../web/navigation.js';
import * as THREE from '../web/vendor/three.module.js';
import {geometryModule} from './geometry-module.mjs';
import {ideaDisplays} from '../web/idea-display.js';
const scene=await geometryModule(),house=starter();for(let n=0;n<12;n++)house.ideas.push({id:'i'+n,roomId:'math',title:'Idea '+n,text:'Note',cue:['crystal','ring','sphere','book'][n%4]});
let walking;
for(const [walk,exterior] of [[false,false],[true,false],[false,true]]){
 const built=scene.buildHouse(house,walk,exterior);if(walk)walking=built;assert.equal(built.floors.length,6);assert.equal(built.objects.length,36);assert.equal(built.ceilings.length,walk||exterior?6:0);
 let meshes=0;built.group.traverse(o=>{if(!o.geometry)return;meshes++;assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));assert.ok([o.position.x,o.position.y,o.position.z,o.rotation.x,o.rotation.y,o.rotation.z].every(Number.isFinite));});
 for(const d of house.doors){const edge=sharedEdge(house.rooms.find(r=>r.id===d.a),house.rooms.find(r=>r.id===d.b)),c=(edge.lo+edge.hi)/2;for(let step=-.4;step<=.4;step+=.05){const x=edge.axis==='x'?c-10:edge.fixed-10+step,z=edge.axis==='z'?c-8:edge.fixed-8+step;assert.ok(scene.canStandAt(house,built.walls,x,z),'Door '+d.a+' / '+d.b);}}
 assert.equal(scene.canStandAt(house,built.walls,-10,-5),false);assert.equal(scene.canStandAt(house,built.walls,-14,0),false);console.log((exterior?'Exterior':walk?'Enclosed walking':'Cutaway')+': '+meshes+' finite meshes, expected floors/objects/ceilings, all 7 doorways pass.');
}
for(const startRoom of house.rooms)for(const target of house.rooms){const start=centerOf(startRoom),path=walkingRoute(house,start,target.id);assert.ok(path.length);let frames=0,total=0;while(path.length&&frames++<10000){const step=stepAlongPath(start,path,.03,(x,z)=>canExploreAt(house,walking.walls,x,z));assert.ok(step.moved>0||step.finished,'Resident stuck: '+startRoom.id+' / '+target.id);total+=step.moved;}assert.ok(frames<10000);assert.equal(roomAtPoint(house,start.x,start.z),target.id);}
const e=entranceFor(house);for(let z=e.z-1;z<=e.z+2;z+=.05)assert.ok(canExploreAt(house,walking.walls,e.x,z),'Front entry blocks at '+z);
assert.ok(walking.frontDoor?.leaf,'A physical front door is available');assert.equal(walking.frontDoor.open,false,'The arrival door starts closed');for(const ceiling of walking.ceilings)assert.ok(Math.abs(ceiling.position.y-ceiling.geometry.parameters.height/2-2.8)<.001,'Ceilings enclose the occupied home');const roofs=[];walking.group.updateMatrixWorld(true);walking.group.traverse(o=>{if(o.userData.roof)roofs.push(new THREE.Box3().setFromObject(o));});assert.ok(roofs.length>=2&&Math.max(...roofs.map(b=>b.max.y))>5,'The house has a tall pitched roof');
const passable=(x,z)=>canExploreAt(house,walking.walls,x,z)&&canOccupy(walking.obstacles,x,z,.2),free=r=>{const c=centerOf(r);if(passable(c.x,c.z))return c;const points=[];for(let x=r.x-10+.3;x<r.x+r.w-10-.3;x+=.28)for(let z=r.y-8+.3;z<r.y+r.h-8-.3;z+=.28)if(passable(x,z))points.push({x,z});return points.sort((a,b)=>Math.hypot(a.x-c.x,a.z-c.z)-Math.hypot(b.x-c.x,b.z-c.z))[0];};
for(const startRoom of house.rooms)for(const targetRoom of house.rooms){const start={...free(startRoom)},target=free(targetRoom),path=findWalkingPath(house,walking.walls,start,target,.28,passable);assert.ok(path.length,'A furnishing-safe route exists: '+startRoom.id+' / '+targetRoom.id);let frames=0;while(path.length&&frames++<20000){const step=stepAlongPath(start,path,.03,passable);assert.ok(step.moved>0||step.finished,'Resident route avoids furnishings: '+startRoom.id+' / '+targetRoom.id);}assert.ok(frames<20000);}
const arrivalBounds=houseBounds(house),arrival={x:arrivalBounds.maxX+6.2,z:e.z+12},entryTarget={x:e.x,z:e.z-1},entryPath=findWalkingPath(house,walking.walls,arrival,entryTarget,.28,passable);assert.ok(entryPath.length,'Full-house arrival connects continuously to the entry');let entryFrames=0;while(entryPath.length&&entryFrames++<20000){const step=stepAlongPath(arrival,entryPath,.03,passable);assert.ok(step.moved>0||step.finished,'Arrival route stops at '+JSON.stringify(arrival)+' next '+JSON.stringify(entryPath[0]));}assert.ok(entryFrames<20000);assert.ok(Math.hypot(arrival.x-entryTarget.x,arrival.z-entryTarget.z)<.03,'Arrives inside through the front door');
const b=houseBounds(house);for(const start of [{x:e.x,z:e.z+5},{x:b.minX-2,z:b.cz},{x:b.maxX+2,z:b.cz},{x:b.cx,z:b.minZ-2}]){const target={x:e.x,z:e.z-1},path=findWalkingPath(house,walking.walls,start,target);assert.ok(path.length,'No outside entry path');let frames=0;while(path.length&&frames++<20000){const step=stepAlongPath(start,path,.03,(x,z)=>canExploreAt(house,walking.walls,x,z));assert.ok(step.moved>0||step.finished,'Outdoor route blocked');}assert.ok(frames<20000);assert.ok(Math.hypot(start.x-target.x,start.z-target.z)<.03);}
const disconnected={...house,doors:[]};assert.deepEqual(roomRoute(disconnected,'math','art'),[]);assert.deepEqual(walkingRoute(disconnected,centerOf(house.rooms[0]),'art'),[]);
const featured=structuredClone(house);featured.resident={roomFeatures:['discussion_circle','question_board','reflection_lamp','experiment_table'].map((type,n)=>({id:'f'+n,type,roomId:house.rooms[n].id})).concat([{id:'stale',type:'reflection_lamp',roomId:'deleted'}])};const withFeatures=scene.buildHouse(featured,true);let features=0;withFeatures.group.traverse(o=>{if(o.userData.featureId)features++;});assert.equal(features,4);
function assertSeparateFeatures(input,roomId){const room=input.rooms.find(r=>r.id===roomId),copy=structuredClone(input);copy.resident={roomFeatures:['discussion_circle','question_board','reflection_lamp','experiment_table'].map((type,n)=>({id:'same-room-'+n,type,roomId}))};const built=scene.buildHouse(copy,true),boxes=[],anchors=[];built.group.updateMatrixWorld(true);built.group.traverse(o=>{if(o.userData.featureId){boxes.push(new THREE.Box3().setFromObject(o));anchors.push(o.userData.anchor);}});assert.equal(boxes.length,4,'All four approved additions remain visible');assert.equal(new Set(anchors.map(a=>a.x+':'+a.z)).size,4,'Distinct furnishing anchors');for(const box of boxes){assert.ok(box.min.x>=room.x-10+.08&&box.max.x<=room.x+room.w-10-.08&&box.min.z>=room.y-8+.08&&box.max.z<=room.y+room.h-8-.08,'Furnishings inside room walls');}for(let a=0;a<boxes.length;a++)for(let b=a+1;b<boxes.length;b++){assert.ok(boxes[a].max.x<=boxes[b].min.x||boxes[b].max.x<=boxes[a].min.x||boxes[a].max.z<=boxes[b].min.z||boxes[b].max.z<=boxes[a].min.z,'Approved additions have separate footprints');}}
for(const room of house.rooms)assertSeparateFeatures(house,room.id);
for(const room of starter().rooms)for(const types of [['question_board'],['discussion_circle','question_board','reflection_lamp','experiment_table']]){const input=starter();input.resident={roomFeatures:types.map((type,n)=>({id:'anchor-feature-'+n,type,roomId:room.id}))};const built=scene.buildHouse(input,true);for(const action of built.interactions)if(action.anchor)assert.ok(canOccupy(built.obstacles,action.anchor.x,action.anchor.z,.2),'Approved additions leave household action usable: '+room.id+' / '+action.label);}
const dense=starter();for(const room of dense.rooms)for(let n=0;n<12;n++)dense.ideas.push({id:room.id+'-'+n,roomId:room.id,title:'Idea '+n,text:'Note',cue:['book','crystal','ring','sphere'][n%4]});const denseBuilt=scene.buildHouse(dense,true),densePassable=(x,z)=>canExploreAt(dense,denseBuilt.walls,x,z)&&canOccupy(denseBuilt.obstacles,x,z,.2);for(const from of dense.rooms)for(const to of dense.rooms){const start={...centerOf(from)},target=centerOf(to),path=findWalkingPath(dense,denseBuilt.walls,start,target,.28,densePassable);assert.ok(path.length,'A fully populated house retains route '+from.id+' / '+to.id);let frames=0;while(path.length&&frames++<20000){const step=stepAlongPath(start,path,.03,densePassable);assert.ok(step.moved>0||step.finished,'Dense collection blocks '+from.id+' / '+to.id);}assert.ok(frames<20000);}for(const action of denseBuilt.interactions)if(action.anchor)assert.ok(canOccupy(denseBuilt.obstacles,action.anchor.x,action.anchor.z,.2),'Full collections retain a usable household anchor');
const surrounded={rooms:[{id:'center',name:'Center',purpose:'',color:'#428d83',x:3,y:3,w:3,h:3},...[[3,0],[0,3],[6,3],[3,6]].map(([x,y],n)=>({id:'neighbor'+n,name:'Neighbor',purpose:'',color:'#428d83',x,y,w:3,h:3}))],doors:[0,1,2,3].map(n=>({a:'center',b:'neighbor'+n})),ideas:[]};assertSeparateFeatures(surrounded,'center');
const offset=structuredClone(surrounded);offset.rooms[1].x=4;offset.rooms[2].y=4;offset.rooms[3].y=2;offset.rooms[4].x=2;for(let n=0;n<12;n++)offset.ideas.push({id:'corner-'+n,roomId:'center',title:'Idea',text:'Note',cue:['book','sphere','ring','crystal'][n%4]});const display=ideaDisplays(offset,offset.rooms[0]);assert.ok(display.cabinets.length>0);assert.equal(display.slots.length,12);for(const d of offset.doors){const edge=sharedEdge(offset.rooms[0],offset.rooms.find(r=>r.id===d.b)),c=(edge.lo+edge.hi)/2;for(const cabinet of display.cabinets){const door=edge.axis==='x'?{minX:c-10-.8,maxX:c-10+.8,minZ:edge.fixed-8-.4,maxZ:edge.fixed-8+.4}:{minX:edge.fixed-10-.4,maxX:edge.fixed-10+.4,minZ:c-8-.8,maxZ:c-8+.8};assert.ok(cabinet.maxX<=door.minX||cabinet.minX>=door.maxX||cabinet.maxZ<=door.minZ||cabinet.minZ>=door.maxZ,'Dense cabinets avoid offset door openings');}}assert.ok(display.slots.every(s=>s.y+.43*s.scale<2.75),'Dense collections remain below ceilings');
for(const r of house.rooms){const one={rooms:[{...r,x:0,y:0,w:3,h:3}],doors:[],ideas:[]};validateHouse(one);assertSeparateFeatures(one,r.id);for(const exterior of [false,true]){const built=scene.buildHouse(one,!exterior,exterior);built.group.traverse(o=>{if(o.geometry)assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));});}}
console.log('All 36 resident room routes avoid walls and actual furnishings; tall roof/2.8m ceilings/physical front door verified; continuous entry routes from all 4 yard sides; disconnected routes rejected; 4 approved features rendered/stale room ignored; minimum rooms finite.');

