import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {starter,sharedEdge,validateHouse} from '../web/model.js';
import {centerOf,entranceFor,roomRoute,walkingRoute,stepAlongPath,canExploreAt,findWalkingPath,roomAtPoint,houseBounds} from '../web/navigation.js';
import * as THREE from '../web/vendor/three.module.js';
let source=await fs.readFile(new URL('../web/scene.js',import.meta.url),'utf8');source=source.replace(/import \{OrbitControls\}[^\n]+/,'const OrbitControls=undefined;');
for(const file of ['./vendor/three.module.js','./model.js','./joystick.js','./navigation.js'])source=source.replace(file,new URL('../web/'+file.slice(2),import.meta.url).href);
const scene=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),house=starter();for(let n=0;n<12;n++)house.ideas.push({id:'i'+n,roomId:'math',title:'Idea '+n,text:'Note',cue:['crystal','ring','sphere','book'][n%4]});
let walking;
for(const [walk,exterior] of [[false,false],[true,false],[false,true]]){
 const built=scene.buildHouse(house,walk,exterior);if(walk)walking=built;assert.equal(built.floors.length,6);assert.equal(built.objects.length,36);assert.equal(built.ceilings.length,walk||exterior?6:0);
 let meshes=0;built.group.traverse(o=>{if(!o.geometry)return;meshes++;assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));assert.ok([o.position.x,o.position.y,o.position.z,o.rotation.x,o.rotation.y,o.rotation.z].every(Number.isFinite));});
 for(const d of house.doors){const edge=sharedEdge(house.rooms.find(r=>r.id===d.a),house.rooms.find(r=>r.id===d.b)),c=(edge.lo+edge.hi)/2;for(let step=-.4;step<=.4;step+=.05){const x=edge.axis==='x'?c-10:edge.fixed-10+step,z=edge.axis==='z'?c-8:edge.fixed-8+step;assert.ok(scene.canStandAt(house,built.walls,x,z),'Door '+d.a+' / '+d.b);}}
 assert.equal(scene.canStandAt(house,built.walls,-10,-5),false);assert.equal(scene.canStandAt(house,built.walls,-14,0),false);console.log((exterior?'Exterior':walk?'Enclosed walking':'Cutaway')+': '+meshes+' finite meshes, expected floors/objects/ceilings, all 7 doorways pass.');
}
for(const startRoom of house.rooms)for(const target of house.rooms){const start=centerOf(startRoom),path=walkingRoute(house,start,target.id);assert.ok(path.length);let frames=0,total=0;while(path.length&&frames++<10000){const step=stepAlongPath(start,path,.03,(x,z)=>canExploreAt(house,walking.walls,x,z));assert.ok(step.moved>0||step.finished,'Resident stuck: '+startRoom.id+' / '+target.id);total+=step.moved;}assert.ok(frames<10000);assert.equal(roomAtPoint(house,start.x,start.z),target.id);}
const e=entranceFor(house);for(let z=e.z-1;z<=e.z+2;z+=.05)assert.ok(canExploreAt(house,walking.walls,e.x,z),'Front entry blocks at '+z);
const b=houseBounds(house);for(const start of [{x:e.x,z:e.z+5},{x:b.minX-2,z:b.cz},{x:b.maxX+2,z:b.cz},{x:b.cx,z:b.minZ-2}]){const target={x:e.x,z:e.z-1},path=findWalkingPath(house,walking.walls,start,target);assert.ok(path.length,'No outside entry path');let frames=0;while(path.length&&frames++<20000){const step=stepAlongPath(start,path,.03,(x,z)=>canExploreAt(house,walking.walls,x,z));assert.ok(step.moved>0||step.finished,'Outdoor route blocked');}assert.ok(frames<20000);assert.ok(Math.hypot(start.x-target.x,start.z-target.z)<.03);}
const disconnected={...house,doors:[]};assert.deepEqual(roomRoute(disconnected,'math','art'),[]);assert.deepEqual(walkingRoute(disconnected,centerOf(house.rooms[0]),'art'),[]);
const featured=structuredClone(house);featured.resident={roomFeatures:['discussion_circle','question_board','reflection_lamp','experiment_table'].map((type,n)=>({id:'f'+n,type,roomId:house.rooms[n].id})).concat([{id:'stale',type:'reflection_lamp',roomId:'deleted'}])};const withFeatures=scene.buildHouse(featured,true);let features=0;withFeatures.group.traverse(o=>{if(o.userData.featureId)features++;});assert.equal(features,4);
function assertSeparateFeatures(input,roomId){const room=input.rooms.find(r=>r.id===roomId),copy=structuredClone(input);copy.resident={roomFeatures:['discussion_circle','question_board','reflection_lamp','experiment_table'].map((type,n)=>({id:'same-room-'+n,type,roomId}))};const built=scene.buildHouse(copy,true),boxes=[],anchors=[];built.group.updateMatrixWorld(true);built.group.traverse(o=>{if(o.userData.featureId){boxes.push(new THREE.Box3().setFromObject(o));anchors.push(o.userData.anchor);}});assert.equal(boxes.length,4,'All four approved additions remain visible');assert.equal(new Set(anchors.map(a=>a.x+':'+a.z)).size,4,'Distinct furnishing anchors');for(const box of boxes){assert.ok(box.min.x>=room.x-10+.08&&box.max.x<=room.x+room.w-10-.08&&box.min.z>=room.y-8+.08&&box.max.z<=room.y+room.h-8-.08,'Furnishings inside room walls');}for(let a=0;a<boxes.length;a++)for(let b=a+1;b<boxes.length;b++){assert.ok(boxes[a].max.x<=boxes[b].min.x||boxes[b].max.x<=boxes[a].min.x||boxes[a].max.z<=boxes[b].min.z||boxes[b].max.z<=boxes[a].min.z,'Approved additions have separate footprints');}}
for(const room of house.rooms)assertSeparateFeatures(house,room.id);
const surrounded={rooms:[{id:'center',name:'Center',purpose:'',color:'#428d83',x:3,y:3,w:3,h:3},...[[3,0],[0,3],[6,3],[3,6]].map(([x,y],n)=>({id:'neighbor'+n,name:'Neighbor',purpose:'',color:'#428d83',x,y,w:3,h:3}))],doors:[0,1,2,3].map(n=>({a:'center',b:'neighbor'+n})),ideas:[]};assertSeparateFeatures(surrounded,'center');
for(const r of house.rooms){const one={rooms:[{...r,x:0,y:0,w:3,h:3}],doors:[],ideas:[]};validateHouse(one);assertSeparateFeatures(one,r.id);for(const exterior of [false,true]){const built=scene.buildHouse(one,!exterior,exterior);built.group.traverse(o=>{if(o.geometry)assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));});}}
console.log('All 36 resident room routes cross doors safely; front doorway traversable; continuous entry routes from all 4 yard sides; disconnected routes rejected; 4 approved features rendered/stale room ignored; minimum rooms finite.');

