import {starter,clone,validateHouse,sharedEdge,reachableRooms,CUES,GRID} from './model.js';
import {createScene} from './scene.js';
import {initLearning} from './learning-ui.js';
import {initResidentUI} from './resident-ui.js';
const $=id=>document.getElementById(id),symbols={crystal:'◇',ring:'◎',sphere:'●',book:'▤'};
let house=starter(),revision=0,selected=house.rooms[0].id,loaded=false,saving=false,plan=null,planSelected=null,drawing=false,drag=null,ideaEditing=null;
const preview=document.body.dataset?.mode==='preview';
const local=document.body.dataset?.mode==='local';
let previewDocument=starter(),previewRevision=0,learningUI=null,residentUI=null,localSettings=null;
document.body.classList.add('immersive');
if(preview)$('preview-banner').hidden=false;
async function getLocalConfig(){if(!local)return {gpt:{ready:false}};if(!localSettings){const response=await fetch('/api/config');const data=await response.json();if(!response.ok)throw Error(data.error||'Could not open local settings.');localSettings=data;}return localSettings;}
async function localRequest(path,options={}){const config=await getLocalConfig();const response=await fetch(path,{...options,headers:{...options.headers,'X-Local-CSRF':config.csrfToken}});const data=await response.json();if(!response.ok)throw Error(data.error||'The local request failed.');return data;}
async function gptConnect(apiKey,model){const data=await localRequest('/api/gpt/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey,model})});localSettings={...localSettings,gpt:data.gpt};return data;}
async function gptDisconnect(){const data=await localRequest('/api/gpt/disconnect',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});localSettings={...localSettings,gpt:data.gpt};return data;}
async function gptChat(message,roomId){if(!loaded||saving)throw Error('Wait for the current save to finish.');saving=true;status('Talking with GPT…');render();try{const data=await localRequest('/api/gpt/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,roomId,revision})});house=validateHouse(data.house);revision=data.revision;scene?.load(house);status('Saved on this computer');return data;}catch(error){status(error.message,true);throw error;}finally{saving=false;render();}}
async function houseRequest(options={}){
 if(!preview){if(local){const config=await getLocalConfig();options={...options,headers:{...options.headers,'X-Local-CSRF':config.csrfToken}};}return fetch('/api/house',options);}
 if(options.method==='PUT'){const data=JSON.parse(options.body);if(data.revision!==previewRevision)return {ok:false,json:async()=>({error:'This preview changed. Reload before saving.'})};previewDocument=validateHouse(data.house);previewRevision++;}
 return {ok:true,json:async()=>({house:clone(previewDocument),revision:previewRevision})};
}
let scene=null;try{scene=createScene($('scene'),data=>{if(data.resident){residentUI?.show();return;}if(data.roomId)selectRoom(data.roomId,false);if(data.ideaId)openIdea(data.ideaId);});scene.load(house);}catch(e){console.error('3D view unavailable',e);$('scene-error').hidden=false;}
const inPlan=()=>!$('plan-workspace').hidden;
function status(text,error=false){$('save-state').textContent=text;document.querySelector('.save-area').classList.toggle('error',error);}
function roomButton(room,count){const button=document.createElement('button');button.className='room-button'+((inPlan()?planSelected:selected)===room.id?' active':'');const dot=document.createElement('i');dot.style.background=room.color;const name=document.createElement('span');name.textContent=room.name;const small=document.createElement('small');small.textContent=count;button.append(dot,name,small);button.onclick=()=>inPlan()?selectPlanRoom(room.id):selectRoom(room.id);return button;}
function render(){
 const current=inPlan()?plan:house;const list=$('room-list');list.replaceChildren(...current.rooms.map(r=>roomButton(r,house.ideas.filter(i=>i.roomId===r.id).length)));$('room-count').textContent=current.rooms.length;
 const room=house.rooms.find(r=>r.id===selected)||house.rooms[0];selected=room.id;$('room-name').textContent=room.name;$('room-purpose').textContent=room.purpose;$('scene-room').textContent=scene?.exterior?'HOUSE OF IDEAS':room.name;
 const ideas=house.ideas.filter(i=>i.roomId===selected);$('idea-list').replaceChildren(...ideas.map(i=>{const b=document.createElement('button');b.className='idea-card';const symbol=document.createElement('span');symbol.className='cue-symbol';symbol.textContent=symbols[i.cue];symbol.style.color=room.color;const title=document.createElement('span');title.textContent=i.title;const note=document.createElement('small');note.textContent=i.text?i.text.slice(0,85)+(i.text.length>85?'…':''):'A '+i.cue+' in this room';b.append(symbol,title,note);b.onclick=()=>openIdea(i.id);return b;}));$('empty-room').hidden=ideas.length>0;
 $('house-stats').textContent=house.rooms.length+' rooms · '+house.ideas.length+' ideas';$('add-idea').disabled=!loaded||saving||ideas.length>=12;$('rename-room').disabled=!loaded||saving;$('apply-plan').disabled=!loaded||saving;$('plan-tab').disabled=!loaded||saving;learningUI?.render();residentUI?.render();
}
function selectRoom(id,move=true){if(!house.rooms.some(r=>r.id===id))return;selected=id;if(move)scene?.select(id);render();learningUI?.noteVisit(id);}
async function load(){status('Opening house…');$('retry').hidden=true;try{const response=await houseRequest();const data=await response.json();if(!response.ok)throw Error(data.error||'Could not open the house.');house=validateHouse(data.house);revision=data.revision;loaded=true;scene?.load(house);render();status(preview?'Preview · this visit only':local?'Saved on this computer':'All changes saved');await learningUI?.onLoad();await residentUI?.onLoad();}catch(e){status(e.message,true);$('retry').hidden=false;loaded=false;scene?.load(house);render();}}
async function saveHouse(next){
 if(!loaded)throw Error('Open your saved house before editing.');if(saving)throw Error('Wait for the current save to finish.');next=validateHouse(learningUI?.includeVisits(next)||next);saving=true;status('Saving…');render();
 try{const response=await houseRequest({method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({house:next,revision})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not save. Please try again.');revision=data.revision;house=next;scene?.load(house);render();status(preview?'Preview · this visit only':local?'Saved on this computer':'All changes saved');return house;}catch(e){status(e.message,true);throw e;}finally{saving=false;render();}
}
function fillRooms(select,value){select.replaceChildren(...house.rooms.map(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=r.name;return o;}));select.value=value;}
function openIdea(id=null){
 if(!loaded||saving)return;ideaEditing=id;const idea=house.ideas.find(i=>i.id===id);$('idea-title').value=idea?.title||'';$('idea-text').value=idea?.text||'';fillRooms($('idea-room'),idea?.roomId||selected);document.querySelector(`input[name="cue"][value="${idea?.cue||'crystal'}"]`).checked=true;
 $('idea-room-label').textContent=house.rooms.find(r=>r.id===(idea?.roomId||selected)).name;$('idea-dialog-title').textContent=idea?'Your idea':'Place an idea';$('delete-idea').hidden=!idea;$('idea-message').textContent='';$('idea-dialog').showModal();
}
async function saveIdea(input,id=ideaEditing){
 const next=clone(house),record={id:id||crypto.randomUUID(),roomId:input.roomId,title:input.title,text:input.text,cue:input.cue};const index=next.ideas.findIndex(i=>i.id===record.id);if(index<0)next.ideas.push(record);else next.ideas[index]=record;
 await saveHouse(next);selectRoom(record.roomId);return record;
}
$('add-idea').onclick=()=>openIdea();$('idea-form').onsubmit=async e=>{e.preventDefault();$('idea-message').textContent='';const button=e.submitter;button.disabled=true;try{await saveIdea({title:$('idea-title').value,text:$('idea-text').value,roomId:$('idea-room').value,cue:document.querySelector('input[name="cue"]:checked').value});$('idea-dialog').close();}catch(err){$('idea-message').textContent=err.message;}finally{button.disabled=false;}};
$('delete-idea').onclick=async()=>{if(!ideaEditing)return;try{const next=clone(house);next.ideas=next.ideas.filter(i=>i.id!==ideaEditing);await saveHouse(next);$('idea-dialog').close();}catch(e){$('idea-message').textContent=e.message;}};
$('idea-room').onchange=()=>{$('idea-room-label').textContent=house.rooms.find(r=>r.id===$('idea-room').value).name;};
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('rename-room').onclick=()=>{const room=house.rooms.find(r=>r.id===selected);$('theme-name').value=room.name;$('theme-purpose').value=room.purpose;$('theme-color').value=room.color;$('theme-message').textContent='';$('room-dialog').showModal();};
$('theme-form').onsubmit=async e=>{e.preventDefault();try{const next=clone(house),r=next.rooms.find(r=>r.id===selected);r.name=$('theme-name').value;r.purpose=$('theme-purpose').value;r.color=$('theme-color').value;await saveHouse(next);$('room-dialog').close();}catch(err){$('theme-message').textContent=err.message;}};
$('retry').onclick=load;
function setView(walk){scene?.setWalk(walk);$('exterior').classList.remove('selected');$('enter-house').hidden=true;$('house-welcome').hidden=true;$('walk').classList.toggle('selected',walk);$('overview').classList.toggle('selected',!walk);$('view-hint').textContent=walk?'WASD to walk · Drag to look · E to talk to Socrates':'Drag to orbit · Scroll to zoom · Select a room or object';$('joystick-label').textContent=walk?'Walk · WASD':'Move view';}
$('exterior').onclick=()=>{scene?.setExterior?.(true);$('exterior').classList.add('selected');$('overview').classList.remove('selected');$('walk').classList.remove('selected');$('enter-house').hidden=false;$('house-welcome').hidden=false;$('view-hint').textContent='Open the door, explore a room, and learn something worth keeping.';render();};
$('enter-house').onclick=()=>{setView(true);scene?.enterHouse?.();};
$('walk').onclick=()=>{setView(true);selectRoom(selected,false);};$('overview').onclick=()=>{setView(false);selectRoom(selected,false);};$('reset-view').onclick=()=>scene?.reset();
function setPlan(show){
 if(show){learningUI?.hideCritic();residentUI?.close();}if(show&&!plan){plan=clone(house);planSelected=selected;}if(show)plan.ideas=clone(house.ideas);document.body.classList.toggle('plan-mode',show);$('resident-hud').hidden=show;$('plan-workspace').hidden=!show;$('house-overlay').hidden=show;$('room-panel').hidden=show;$('plan-panel').hidden=!show;$('plan-tab').classList.toggle('selected',show);$('house-tab').classList.toggle('selected',!show);
 if(show){renderPlan();fillPlanForm();}else{drawing=false;drag=null;$('draw-room').classList.remove('pending');$('draw-room').textContent='Draw a room';$('plan-grid').classList.remove('drawing');$('plan-instruction').textContent='Select a room, or draw a new one. One cell = one metre.';}render();
}
// A staged plan remains editable until Build or Discard. The house shows saved geometry.
$('rooms-toggle').onclick=()=>{const show=document.body.classList.toggle('rooms-open');$('rooms-toggle').setAttribute('aria-expanded',String(show));};
$('plan-tab').onclick=()=>setPlan(true);$('house-tab').onclick=()=>{learningUI?.hideCritic();residentUI?.close();if(plan){$('plan-message').textContent='Your layout draft is kept. Use Build this house to apply it.';}setPlan(false);setView(true);};
function selectPlanRoom(id){planSelected=id;drawing=false;$('draw-room').classList.remove('pending');$('draw-room').textContent='Draw a room';$('plan-grid').classList.remove('drawing');fillPlanForm();renderPlan();render();}
function fillPlanForm(){
 const r=plan.rooms.find(r=>r.id===planSelected)||plan.rooms[0];planSelected=r.id;for(const key of ['name','purpose','color','x','y','w','h'])$('plan-'+key).value=r[key];
 const neighbors=plan.rooms.filter(b=>b!==r&&sharedEdge(r,b)&&!plan.doors.some(d=>(d.a===r.id&&d.b===b.id)||(d.b===r.id&&d.a===b.id)));
 $('door-target').replaceChildren(...neighbors.map(b=>{const o=document.createElement('option');o.value=b.id;o.textContent=b.name;return o;}));if(!neighbors.length){const o=document.createElement('option');o.textContent='No unconnected adjacent rooms';o.value='';$('door-target').append(o);}$('add-door').disabled=!neighbors.length;
 $('door-list').replaceChildren(...plan.doors.filter(d=>d.a===r.id||d.b===r.id).map(d=>{const div=document.createElement('div');div.className='door-row';const span=document.createElement('span');span.textContent=plan.rooms.find(b=>b.id===(d.a===r.id?d.b:d.a)).name;const b=document.createElement('button');b.textContent='Remove';b.onclick=()=>{plan.doors=plan.doors.filter(x=>x!==d);refreshPlan();};div.append(span,b);return div;}));
}
function refreshPlan(){fillPlanForm();renderPlan();render();}
function cleanDoors(candidate){candidate.doors=candidate.doors.filter(d=>{const a=candidate.rooms.find(r=>r.id===d.a),b=candidate.rooms.find(r=>r.id===d.b);return a&&b&&sharedEdge(a,b);});}
$('room-form').onsubmit=e=>{e.preventDefault();const next=clone(plan),r=next.rooms.find(r=>r.id===planSelected);for(const key of ['name','purpose','color'])r[key]=$('plan-'+key).value;for(const key of ['x','y','w','h'])r[key]=Number($('plan-'+key).value);try{const previous=next.doors.length;cleanDoors(next);plan=validateHouse(next);$('plan-message').textContent=previous>plan.doors.length?'Updated. Doors without a shared wall were removed.':'Room updated in your layout draft.';refreshPlan();}catch(err){$('plan-message').textContent=err.message;}};
$('remove-room').onclick=()=>{if(plan.rooms.length===1){$('plan-message').textContent='Keep at least one room.';return;}if(plan.ideas.some(i=>i.roomId===planSelected)){$('plan-message').textContent='Move this room’s ideas to another room before removing it.';return;}plan.rooms=plan.rooms.filter(r=>r.id!==planSelected);cleanDoors(plan);planSelected=plan.rooms[0].id;refreshPlan();};
$('add-door').onclick=()=>{if(!$('door-target').value)return;plan.doors.push({a:planSelected,b:$('door-target').value});refreshPlan();};
$('draw-room').onclick=()=>{drawing=!drawing;$('draw-room').classList.toggle('pending',drawing);$('draw-room').textContent=drawing?'Drawing… click to cancel':'Draw a room';$('plan-grid').classList.toggle('drawing',drawing);$('plan-instruction').textContent=drawing?'Drag across empty cells to draw a room of at least 3 × 3.':'Select a room, or draw a new one. One cell = one metre.';};
const ns='http://www.w3.org/2000/svg';function svgEl(name,attrs={}){const el=document.createElementNS(ns,name);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);return el;}
function renderPlan(){
 const svg=$('plan-grid');svg.replaceChildren();const unitPx=(svg.clientWidth||630)/21,nameSize=Math.max(.43,14/unitPx),metaSize=Math.max(.33,12/unitPx);const grid=svgEl('g',{'stroke':'#ccd9df','stroke-width':'.025'});for(let x=0;x<=20;x++)grid.append(svgEl('line',{x1:x,x2:x,y1:0,y2:16}));for(let y=0;y<=16;y++)grid.append(svgEl('line',{x1:0,x2:20,y1:y,y2:y}));svg.append(grid);
 for(const r of plan.rooms){const g=svgEl('g',{tabindex:0,role:'button','aria-label':r.name+', '+r.w+' by '+r.h+' metres'});const rect=svgEl('rect',{x:r.x+.055,y:r.y+.055,width:r.w-.11,height:r.h-.11,fill:r.color,'fill-opacity':r.id===planSelected?'.3':'.16',stroke:r.id===planSelected?'#192b35':r.color,'stroke-width':r.id===planSelected?'.1':'.055',rx:'.06'});const text=svgEl('text',{x:r.x+r.w/2,y:r.y+r.h/2-nameSize*.15,'text-anchor':'middle','font-size':nameSize,fill:'#243e4a','font-family':'system-ui',style:'pointer-events:none'});const limit=Math.max(4,Math.min(22,Math.floor((r.w-.6)/nameSize*1.8)));text.textContent=r.name.length>limit?r.name.slice(0,limit-1)+'…':r.name;const size=svgEl('text',{x:r.x+r.w/2,y:r.y+r.h/2+nameSize*.95,'text-anchor':'middle','font-size':metaSize,fill:'#526a78',style:'pointer-events:none'});size.textContent=r.w+' × '+r.h;g.append(rect,text,size);g.onclick=e=>{if(!drawing)selectPlanRoom(r.id);};g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectPlanRoom(r.id);}};svg.append(g);}
 for(const d of plan.doors){const edge=sharedEdge(plan.rooms.find(r=>r.id===d.a),plan.rooms.find(r=>r.id===d.b));if(!edge)continue;const c=(edge.lo+edge.hi)/2;svg.append(svgEl('line',{x1:edge.axis==='x'?c-.65:edge.fixed,x2:edge.axis==='x'?c+.65:edge.fixed,y1:edge.axis==='z'?c-.65:edge.fixed,y2:edge.axis==='z'?c+.65:edge.fixed,stroke:'#192b35','stroke-width':'.18','stroke-linecap':'round'}));}
 if(drag){const rect=drawRect();svg.append(svgEl('rect',{x:rect.x,y:rect.y,width:rect.w,height:rect.h,fill:'#e8b76a','fill-opacity':'.35',stroke:'#9a6c34','stroke-width':'.08','stroke-dasharray':'.2 .15'}));}
}
function point(e){const p=$('plan-grid').createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform($('plan-grid').getScreenCTM().inverse());return {x:Math.max(0,Math.min(20,Math.round(q.x))),y:Math.max(0,Math.min(16,Math.round(q.y)))};}
function drawRect(){return {x:Math.min(drag.start.x,drag.end.x),y:Math.min(drag.start.y,drag.end.y),w:Math.abs(drag.end.x-drag.start.x),h:Math.abs(drag.end.y-drag.start.y)};}
$('plan-grid').onpointerdown=e=>{if(!drawing||e.button!==0)return;e.preventDefault();drag={id:e.pointerId,start:point(e),end:point(e)};$('plan-grid').setPointerCapture(e.pointerId);renderPlan();};
$('plan-grid').onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;drag.end=point(e);renderPlan();};
$('plan-grid').onpointerup=e=>{if(!drag||e.pointerId!==drag.id)return;drag.end=point(e);const rect=drawRect();drag=null;const r={id:crypto.randomUUID(),name:'New room',purpose:'',color:'#6d91aa',...rect};try{const next=clone(plan);next.rooms.push(r);plan=validateHouse(next);selectPlanRoom(r.id);$('plan-message').textContent='Room added. Give it a theme, then connect it with a door.';}catch(err){$('plan-message').textContent=err.message;renderPlan();}};
$('plan-grid').onpointercancel=()=>{drag=null;renderPlan();};
$('apply-plan').onclick=async()=>{try{const next=clone(plan);next.ideas=clone(house.ideas);if(house.learning)next.learning=clone(house.learning);if(house.resident)next.resident=clone(house.resident);await saveHouse(next);selected=planSelected;plan=null;setPlan(false);selectRoom(selected);$('plan-message').textContent='';}catch(e){$('plan-message').textContent=e.message;}};
$('cancel-plan').onclick=()=>{plan=null;setPlan(false);};
// Keep the room navigator in sync when walking through a door, without moving the camera.
setInterval(()=>{if(scene?.walking&&!inPlan()){const id=scene.roomAt();if(id&&id!==selected)selectRoom(id,false);}},500);
window.addEventListener('resize',()=>{if(inPlan())renderPlan();});
learningUI=initLearning({$,document,window,getHouse:()=>house,getSelected:()=>selected,isLoaded:()=>loaded,isSaving:()=>saving,saveHouse,selectRoom,openHouse:()=>{setPlan(false);document.body.classList.add('rooms-open');},scene,preview});
residentUI=initResidentUI({$,document,window,scene,getHouse:()=>house,getSelected:()=>selected,isLoaded:()=>loaded,isSaving:()=>saving,saveHouse,openHouse:()=>{setPlan(false);setView(true);},local,preview,gptConfig:getLocalConfig,gptConnect,gptDisconnect,gptChat});
render();load();
const context=document.modelContext;if(context?.registerTool){const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(console.error);}catch(e){console.error(e);}};
 register({name:'read_house',title:'Read house',description:'Read the saved rooms, connections, and ideas currently shown in the house.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){if(!loaded)throw Error('House has not loaded.');return clone(house);}});
 register({name:'navigate_to_room',title:'Visit room',description:'Select an existing room and move the 3D view to it. Does not change saved ideas.',inputSchema:{type:'object',properties:{roomId:{type:'string'}},required:['roomId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!house.rooms.some(r=>r.id===input.roomId))throw Error('Unknown room.');if(plan)setPlan(false);selectRoom(input.roomId);return {roomId:selected};}});
 register({name:'save_idea',title:'Save idea',description:'Create and persist an idea with a spatial memory object in an existing room, or update an idea using its id.',inputSchema:{type:'object',properties:{id:{type:'string'},roomId:{type:'string'},title:{type:'string',minLength:1,maxLength:100},text:{type:'string',maxLength:6000},cue:{type:'string',enum:CUES}},required:['roomId','title','text','cue'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){if(!input||typeof input!=='object'||(input.id&&!house.ideas.some(i=>i.id===input.id)))throw Error('Invalid idea.');if(plan)throw Error('Build or discard the layout draft first.');const r=await saveIdea(input,input.id||null);return {id:r.id,roomId:r.roomId,status:'saved'};}});
}
