// Museum records describe real works; bundled cards are original study diagrams.
export const DALI_OBJECTS = [
 {id:'dream-chair',title:'Long-legged dream chair',x:-3,z:1,action:'Sit and compare scale',text:'A useful seat rests below an impossibly tall back. Sketch an ordinary chair, then change one proportion. Which changes its character without losing its use?'},
 {id:'drawer-library',title:'Library of hidden associations',x:4.5,z:0,action:'Open a reading drawer',text:'Choose two ordinary things: a spoon and a cloud, or a book and a window. Write an association between them. Now distinguish a visible resemblance from a private memory.'},
 {id:'soft-clock',title:'Soft clock desk',x:3,z:3,action:'Try a time experiment',text:'Look at one object quietly for thirty seconds. Estimate how much time passed before checking a clock. Describe the difference between measured time and experienced time.'},
 {id:'viewpoint',title:'Impossible sphere viewpoint',x:0,z:-1,action:'Discover a viewpoint',text:'Walk around the floating spheres. From one viewpoint they suggest a face; from another they separate. Draw both views. Does the object change, or does your interpretation?'},
 {id:'egg-window',title:'Egg-shaped landscape window',x:-4.6,z:-1,action:'Frame a dream landscape',text:'Choose three things visible through this opening. Write a scene that keeps their shapes but changes their scale. Keep observation and invention in separate sentences.'}
];
const works=[
 ['memory','The Persistence of Memory','1931','https://www.moma.org/collection/works/79018?locale=en','Compare measured time with remembered time.'],
 ['galatea','Galatea of the Spheres (Gala Placidia)','1952','https://catalogues.salvador-dali.org/catalogues/en/heritageobject/54/','Compare a whole figure with its separate parts.'],
 ['leda','Leda Atomica','1947–49','https://catalogues.salvador-dali.org/catalogues/en/heritageobject/51/','Study the spaces between things that seem suspended.'],
 ['face','Face of the Great Masturbator','1929','https://catalogues.salvador-dali.org/catalogues/en/heritageobject/22-5103/','Separate what you see from what you associate with it.']
];
export const DALI_ARTIST={id:'dali',name:'Salvador Dalí',color:'#d6ad55',background:'#e8dfce',description:'An interpretive resident in an original dream house inspired by Dalí’s interest in surprising associations, scale and viewpoints. This is an imagined residence, not a reconstruction or historical testimony.',websiteUrl:'https://www.salvador-dali.org/en/visit/salvador-dali-house-museum/',approach:'Observe precisely, then test an unexpected association. Keep observation distinct from invention.',works:works.map(([id,title,date,sourceUrl,description])=>({id,title,date,medium:'Painting · museum-linked study',imageUrl:'./dali-house/'+id+'.svg',alt:'Original study card for '+title+'; not a reproduction of the painting.',description:description+' The frame contains an original learning diagram. Open the museum record to see the actual painting.',sourceUrl,rights:'Study diagram made for House of Ideas. Dalí’s painting is not bundled; its reproduction rights remain with the rights holders.',rightsUrl:'https://www.salvador-dali.org/en/dali-foundation/services/rights-and-image/',citation:'Salvador Dalí, '+title+', '+date+'. See the linked museum record.',dimensions:'See museum record',collection:'See museum record'}))};
