import * as THREE from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {validateGlb} from './design-objects.js';
import {entranceFor,yardBounds} from './navigation.js';
import {sharedEdge} from './model.js';

export const DISPLAY_BUDGET=Object.freeze({vertices:600000,triangles:600000,texturePixels:33554432,drawCalls:1024});
function instancedPrimitives(input){const bytes=input instanceof Uint8Array?input:new Uint8Array(input),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),json=JSON.parse(new TextDecoder().decode(bytes.subarray(20,20+view.getUint32(12,true))));return json.nodes.reduce((total,node)=>total+(node.mesh===undefined?0:json.meshes[node.mesh].primitives.length),0);}

export async function parseDesign(bytes,kind='object',scale=1){
 const summary=validateGlb(bytes),drawCalls=summary.drawCalls??instancedPrimitives(bytes);if(drawCalls>512)throw Error('Export fewer than 513 mesh parts or instances for a responsive local exhibit.');const buffer=bytes instanceof ArrayBuffer?bytes:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),gltf=await new GLTFLoader().parseAsync(buffer,'');const root=gltf.scene,images=new Set();let texturePixels=0;
 try{root.traverse(o=>{if(o.isLight||o.isCamera)o.visible=false;if(o.isMesh){for(const a of Object.values(o.geometry.attributes))for(let row=0;row<a.count;row++)for(let component=0;component<a.itemSize;component++)if(!Number.isFinite(a.getComponent(row,component)))throw Error('The model contains non-finite geometry.');for(const material of Array.isArray(o.material)?o.material:[o.material])for(const value of Object.values(material))if(value?.isTexture&&value.image&&!images.has(value.image)){images.add(value.image);texturePixels+=(value.image.width||0)*(value.image.height||0);}o.castShadow=o.receiveShadow=true;}});
 const bounds=new THREE.Box3().setFromObject(root),size=bounds.getSize(new THREE.Vector3());if(![size.x,size.y,size.z].every(Number.isFinite)||Math.max(size.x,size.y,size.z)<=0)throw Error('The model has no visible finite geometry.');
 const dimension=kind==='house'?Math.max(size.x,size.z):Math.max(size.x,size.y,size.z);if(!Number.isFinite(dimension)||dimension<1e-7||!Number.isFinite(scale)||scale<=0)throw Error('The model needs a visible footprint and positive finite scale.');const factor=(kind==='house'?12:1)*scale/dimension;root.position.sub(new THREE.Vector3((bounds.min.x+bounds.max.x)/2,bounds.min.y,(bounds.min.z+bounds.max.z)/2));const wrapper=new THREE.Group();wrapper.add(root);wrapper.scale.setScalar(factor);wrapper.updateMatrixWorld(true);return {group:wrapper,size:size.multiplyScalar(factor),budget:{vertices:summary.vertices,triangles:summary.triangles,texturePixels,drawCalls}};}catch(error){disposeTemplate({group:root});throw error;}
}
const overlaps=(a,b,margin=0)=>a.maxX+margin>b.minX&&a.minX-margin<b.maxX&&a.maxZ+margin>b.minZ&&a.minZ-margin<b.maxZ;
function doorKeepouts(house,roomId){const areas=[];for(const door of house.doors){if(door.a!==roomId&&door.b!==roomId)continue;const a=house.rooms.find(r=>r.id===door.a),b=house.rooms.find(r=>r.id===door.b),edge=a&&b&&sharedEdge(a,b);if(!edge)continue;const x=edge.axis==='x'?(edge.lo+edge.hi)/2-10:edge.fixed-10,z=edge.axis==='x'?edge.fixed-8:(edge.lo+edge.hi)/2-8,rx=edge.axis==='x'?.85:1.1,rz=edge.axis==='x'?1.1:.85;areas.push({minX:x-rx,maxX:x+rx,minZ:z-rz,maxZ:z+rz});}const e=entranceFor(house);if(e.roomId===roomId)areas.push({minX:e.x-.9,maxX:e.x+.9,minZ:e.z-1.15,maxZ:e.z+1.15});return areas;}
export function findDesignPosition(house,roomId,scale,obstacles=[]){const room=house.rooms.find(r=>r.id===roomId);if(!room||!Number.isFinite(scale)||scale<=0)return null;const radius=Math.max(.2,scale/2),cx=room.x+room.w/2-10,cz=room.y+room.h/2-8,keepouts=[...obstacles,...doorKeepouts(house,roomId)],candidates=[];for(let x=room.x-10+radius+.3;x<=room.x+room.w-10-radius-.3;x+=.4)for(let z=room.y-8+radius+.3;z<=room.y+room.h-8-radius-.3;z+=.4){if(Math.abs(x-cx)<.9&&Math.abs(z-cz)<.9)continue;const area={minX:x-radius,maxX:x+radius,minZ:z-radius,maxZ:z+radius};if(keepouts.some(o=>overlaps(area,o,.22)))continue;candidates.push({x,z,d:Math.hypot(x-cx,z-cz)});}candidates.sort((a,b)=>b.d-a.d);const c=candidates[0];return c?[+(c.x-cx).toFixed(3),0,+(c.z-cz).toFixed(3)]:null;}
function disposeTemplate(template){const geometries=new Set(),materials=new Set(),textures=new Set();template.group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const material of o.material?(Array.isArray(o.material)?o.material:[o.material]):[])materials.add(material);});for(const material of materials){for(const value of Object.values(material))if(value?.isTexture)textures.add(value);material.dispose();}for(const texture of textures)texture.dispose();for(const geometry of geometries)geometry.dispose();}
function clearDisplays(group){group.traverse(o=>{if(o.userData.designOwned){o.geometry?.dispose();for(const material of o.material?(Array.isArray(o.material)?o.material:[o.material]):[])material.dispose();}});group.clear();}
export function createDesignLayer(scene,{resolveAsset,onError}){
 const group=new THREE.Group();scene.add(group);const cache=new Map(),tourReferences=new Map();let activeAssets=new Set(),signature='',generation=0,obstacles=[],house=null;
 function discard(id){const promise=cache.get(id);if(!promise)return;cache.delete(id);promise.then(disposeTemplate).catch(()=>{});}
 function prune(){for(const id of cache.keys())if(!activeAssets.has(id)&&!tourReferences.has(id))discard(id);}
 async function template(meta){if(!cache.has(meta.assetId)){const promise=(async()=>{const response=await fetch(resolveAsset(meta.assetId));if(!response.ok)throw Error('The imported model is missing from this computer.');return parseDesign(await response.arrayBuffer());})();cache.set(meta.assetId,promise);promise.catch(()=>{if(cache.get(meta.assetId)===promise)cache.delete(meta.assetId);});}return cache.get(meta.assetId);}
 async function load(next,built,edition){house=next;const designs=edition==='atelier'?next.designObjects||[]:[],key=JSON.stringify([designs,next.rooms.map(r=>[r.id,r.x,r.y,r.w,r.h]),next.doors,built?.obstacles||[]]);if(key===signature)return;signature=key;const epoch=++generation;clearDisplays(group);obstacles=[];activeAssets=new Set(designs.map(meta=>meta.assetId));prune();const renderedAssets=new Set(),budget={vertices:0,triangles:0,texturePixels:0,drawCalls:0};
  for(const meta of designs){let loaded=false;try{const original=await template(meta);loaded=true;if(epoch!==generation)return;const addedPixels=renderedAssets.has(meta.assetId)?0:original.budget.texturePixels;if(budget.vertices+original.budget.vertices>DISPLAY_BUDGET.vertices||budget.triangles+original.budget.triangles>DISPLAY_BUDGET.triangles||budget.texturePixels+addedPixels>DISPLAY_BUDGET.texturePixels||budget.drawCalls+original.budget.drawCalls>DISPLAY_BUDGET.drawCalls)throw Error('The active display is too detailed. Reduce model detail or display fewer designs in this house.');const object=original.group.clone(true),room=next.rooms.find(r=>r.id===meta.roomId),e=entranceFor(next),pos=meta.position;object.rotation.y=meta.rotation;
    if(meta.placement==='room'){if(!room)throw Error('Choose an existing room for this design.');const x=room.x+room.w/2-10+pos[0],z=room.y+room.h/2-8+pos[2];object.position.set(x,pos[1],z);object.scale.multiplyScalar(meta.scale);object.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(object),area={minX:box.min.x,maxX:box.max.x,minZ:box.min.z,maxZ:box.max.z,label:meta.title};if(area.minX<room.x-10+.2||area.maxX>room.x+room.w-10-.2||area.minZ<room.y-8+.2||area.maxZ>room.y+room.h-8-.2||box.min.y<-.1||box.max.y>2.6)throw Error('This model does not fit inside its room. Edit its scale or placement.');if([...(built?.obstacles||[]),...obstacles,...doorKeepouts(next,room.id)].some(o=>overlaps(area,o,.1)))throw Error('This design overlaps furniture or a doorway. Choose a clear position.');obstacles.push(area);}
    else{const index=designs.filter(d=>d.placement==='garden').indexOf(meta);object.scale.multiplyScalar(meta.kind==='house'?.8:meta.scale);object.position.set(e.x+2.4+(index%3)*1.4+pos[0],.5+pos[1],e.z+3.2+Math.floor(index/3)*1.3+pos[2]);object.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(object),area={minX:Math.min(box.min.x,object.position.x-.58),maxX:Math.max(box.max.x,object.position.x+.58),minZ:Math.min(box.min.z,object.position.z-.58),maxZ:Math.max(box.max.z,object.position.z+.58),label:meta.title},yard=yardBounds(next),rooms=next.rooms.map(r=>({minX:r.x-10,maxX:r.x+r.w-10,minZ:r.y-8,maxZ:r.y+r.h-8}));if(area.minX<yard.minX+.3||area.maxX>yard.maxX-.3||area.minZ<yard.minZ+.3||area.maxZ>yard.maxZ-.3)throw Error('Keep the garden exhibit inside the reachable garden.');if([...rooms,...(built?.obstacles||[]),...obstacles,...doorKeepouts(next,e.roomId)].some(o=>overlaps(area,o,.15)))throw Error('This exhibit blocks the house, a doorway or another object. Choose a clear garden position.');const table=new THREE.Mesh(new THREE.CylinderGeometry(.58,.48,.5,16),new THREE.MeshStandardMaterial({color:'#b9ac92'}));table.position.set(object.position.x,.25,object.position.z);table.userData={designId:meta.id,label:'Explore '+meta.title,designOwned:true};group.add(table);obstacles.push(area);}
    object.traverse(o=>{o.userData={designId:meta.id,roomId:meta.roomId,label:meta.title+' · inspect'};});group.add(object);group.updateMatrixWorld(true);budget.vertices+=original.budget.vertices;budget.triangles+=original.budget.triangles;budget.texturePixels+=addedPixels;budget.drawCalls+=original.budget.drawCalls;renderedAssets.add(meta.assetId);
   }catch(error){if(epoch===generation){if(!loaded)signature='';if(!renderedAssets.has(meta.assetId)&&!tourReferences.has(meta.assetId))discard(meta.assetId);onError?.(error.message);}}}
 }
 return {group,load,get obstacles(){return obstacles;},async tour(id){const meta=house?.designObjects?.find(o=>o.id===id);if(!meta)throw Error('Choose an imported design.');tourReferences.set(meta.assetId,(tourReferences.get(meta.assetId)||0)+1);let released=false;const release=()=>{if(released)return;released=true;const count=tourReferences.get(meta.assetId)-1;if(count)tourReferences.set(meta.assetId,count);else tourReferences.delete(meta.assetId);prune();};try{const original=await template(meta),copy=original.group.clone(true),size=original.size.clone(),dimension=Math.max(size.x,size.z);if(meta.kind==='house'&&dimension<1e-7)throw Error('The imported house needs a visible floor footprint.');const factor=meta.kind==='house'?12/dimension*meta.scale:meta.scale;copy.scale.multiplyScalar(factor);copy.userData={designId:id};copy.updateMatrixWorld(true);return {group:copy,size:size.multiplyScalar(factor),meta,release};}catch(error){release();throw error;}},position(house,roomId,scale,built){return findDesignPosition(house,roomId,scale,[...(built?.obstacles||[]),...obstacles]);}};
}
