// Original puzzles. Points reward recorded practice, not a claim of mastery.
export const TRAIL_QUESTS=[
 {id:'code',roomId:'math',title:'The doubling bookshelf',topic:'Patterns',object:'book',lesson:'A rule explains how to move between terms. A finite sequence can fit many rules, so state your assumption.',question:'Assuming each term doubles: 2, 4, 8, 16, __?',choices:['18','24','32','64'],answer:'32',feedback:'Under doubling, 16 × 2 = 32. A different rule could generate a different continuation.',recall:'Make a new doubling sequence and explain why a few numbers alone do not determine a unique rule.'},
 {id:'lock',roomId:'residence-floor-1',title:'The equation lock',topic:'Algebra',object:'ring',lesson:'Keep both sides equal. For 2x + 3 = 11, subtract 3 on both sides, then divide both sides by 2.',question:'Which value opens the lock: 2x + 3 = 11?',choices:['3','4','5','7'],answer:'4',feedback:'x = 4, because 2 × 4 + 3 = 11. Check by substitution.',recall:'Solve 3x + 2 = 17 without the lesson, then explain and check your steps.'},
 {id:'chance',roomId:'work',title:'The mischievous marble bag',topic:'Probability',object:'sphere',lesson:'For equally likely marbles, probability is favourable marbles divided by all marbles. A probability describes a model; it does not promise the next outcome.',question:'A bag holds 3 gold and 1 green marble. What is P(gold) on one random draw?',choices:['1/4','1/2','3/4','1'],answer:'3/4',feedback:'Three of the four equally likely marbles are gold: 3/4. A green draw remains possible.',recall:'Imagine 2 red and 3 blue marbles. Explain P(red) and why five draws need not produce exactly two reds.'},
 {id:'evidence',roomId:'art',title:'The unreliable witness',topic:'Observation',object:'crystal',lesson:'Separate an observation from an explanation. A red surface is visible; being angry is an interpretation that needs more evidence.',question:'Which statement reports an observation rather than guessing a cause?',choices:['The room is red','The owner is angry','Red always makes people angry'],answer:'The room is red',feedback:'The colour can be observed. A claim about somebody’s feelings requires other evidence.',recall:'Describe a painting or object in two sentences: one observation and one interpretation. Say how you would test the interpretation.'},
 {id:'claim',roomId:'questions',title:'The boastful number oracle',topic:'Logic',object:'ring',lesson:'One counterexample disproves a universal claim. Checking many examples can suggest a rule but does not by itself prove it.',question:'The oracle says every prime is odd. Which number disproves it?',choices:['1','2','3','9'],answer:'2',feedback:'2 is prime and even. The narrower true claim is that every prime greater than 2 is odd.',recall:'Invent a universal claim with a counterexample. Rewrite it more carefully, explaining what your example shows.'},
 {id:'route',roomId:'connections',title:'The shortcut that wasn’t',topic:'Geometry',object:'sphere',lesson:'Distance between endpoints differs from path length. In a flat Euclidean plane, perpendicular displacements of 3 and 4 have straight-line length √(3² + 4²).',question:'Walk 3 metres east and 4 north. What is the straight-line displacement?',choices:['1 metre','5 metres','7 metres','12 metres'],answer:'5 metres',feedback:'The displacement is 5 metres; the travelled path is 7. The right-angle assumption matters.',recall:'Explain displacement versus path length using your own route through the house.'}
];
export const trailQuest=id=>TRAIL_QUESTS.find(q=>q.id===id);
export const trailToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const addDays=(date,n)=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const plain=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))throw Error('Use a supported learning trail record.');};
export function validateTrail(input){
 plain(input,['version','activeId','records']);if(input.version!==1||input.activeId!==null&&!trailQuest(input.activeId)||!Array.isArray(input.records)||input.records.length>180)throw Error('The learning trail supports 180 saved attempts; export your progress before extending it. Nothing was removed.');
 const identities=new Set(),practised=new Set(),discovered=new Set(),days=new Set();
 const records=input.records.map(r=>{plain(r,['id','questId','date','kind','answer','explanation']);if(typeof r.id!=='string'||!/^trail-[0-9]+$/.test(r.id)||identities.has(r.id)||!trailQuest(r.questId)||!['discovery','practice','recall'].includes(r.kind)||typeof r.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||!Number.isFinite(Date.parse(r.date+'T12:00:00Z'))||new Date(r.date+'T12:00:00Z').toISOString().slice(0,10)!==r.date||r.date>trailToday()||typeof r.answer!=='string'||r.answer.length>100||typeof r.explanation!=='string'||r.explanation.length>1000)throw Error('Use a valid bounded learning attempt.');identities.add(r.id);
  if(r.kind==='discovery'){if(discovered.has(r.questId)||r.answer||r.explanation)throw Error('An object discovery is recorded once.');discovered.add(r.questId);}
  if(r.kind==='practice'){if(!discovered.has(r.questId)||r.date<input.records.find(x=>x.questId===r.questId&&x.kind==='discovery').date||practised.has(r.questId)||r.answer!==trailQuest(r.questId).answer||r.explanation.trim().length<25)throw Error('Practice needs a discovered object, a checked answer and your explanation.');practised.add(r.questId);}
  if(r.kind==='recall'){const key=r.questId+':'+r.date,last=recordsFor({records:input.records.slice(0,input.records.indexOf(r))},r.questId).filter(x=>x.kind!=='discovery').at(-1);if(!practised.has(r.questId)||days.has(key)||!last||!trailProgress({records:input.records.slice(0,input.records.indexOf(r))},r.questId,r.date).ready||r.explanation.trim().length<25||r.explanation.trim()===last.explanation.trim())throw Error('Recall needs a later day and a new explanation.');days.add(key);}
  return {...r};});return {version:1,activeId:input.activeId,records};
}
export const initialTrail=()=>({version:1,activeId:null,records:[]});
export const recordsFor=(trail,id)=>trail.records.filter(r=>r.questId===id);
export function trailProgress(trail,id,today=trailToday()){const records=recordsFor(trail,id),practice=records.find(r=>r.kind==='practice'),recalls=records.filter(r=>r.kind==='recall'),last=recalls.at(-1)||practice,due=last?addDays(last.date,[1,3,7][Math.min(recalls.length,2)]):null;return {discovered:records.some(r=>r.kind==='discovery'),completed:Boolean(practice),recalls:recalls.length,due,ready:Boolean(due&&today>=due)};}
export function selectTrail(network,id){if(!trailQuest(id))throw Error('Choose a learning quest.');const next=structuredClone(network);next.learningTrail=validateTrail({...(next.learningTrail||initialTrail()),activeId:id});return next;}
export function recordTrail(network,id,kind,{answer='',explanation='',date=trailToday()}={}){const next=selectTrail(network,id),trail=next.learningTrail,progress=trailProgress(trail,id,date),q=trailQuest(id);if(kind==='discovery'&&progress.discovered)return next;if(kind==='practice'&&progress.completed)throw Error('This quest already has its practice stamp. Try a later recall.');if(kind==='recall'&&!progress.ready)throw Error('This recall is due '+progress.due+'. You can still explore today.');if(kind==='practice'&&answer!==q.answer)throw Error('Not yet. Compare your answer with the lesson, then try again.');trail.records.push({id:'trail-'+(trail.records.length+1),questId:id,date,kind,answer,explanation});next.learningTrail=validateTrail(trail);return next;}
export const trailPoints=trail=>trail.records.reduce((n,r)=>n+(r.kind==='practice'?25:r.kind==='recall'?10:0),0);
