import {starter,validateHouse} from './model.js';
import {createResidence} from './residence-data.js';
import {TRAIL_QUESTS} from './learning-trail.js';
export function createPatternHouse(){
 const house=createResidence(starter(),{floors:3});
 const themes={math:['Code library','#737691','A book has been whispering numbers. State a rule before believing it.'],art:['Unreliable witness room','#bb785f','Somebody has confused what they saw with what they guessed. Can you separate them?'],work:['Chance kitchen','#72947e','The marble bag makes promises it cannot keep. Investigate chance without demanding certainty.'],questions:['Oracle’s debate lounge','#ac9459','The number oracle is very confident. Bring it one stubborn counterexample.'],learning:['Detective hall','#789b9b','Welcome, pattern detective. World guide → Learning trail. Find six objects, solve their puzzles, and explain your reasoning.'],connections:['Shortcut laboratory','#956d8e','The shortest-looking route may fool you. Compare a walk with its displacement.'],'residence-floor-1':['Equation vault','#9b7d5a','Upstairs, a ring locks an equation. Balance both sides to open it.'],'residence-floor-2':['Observation tower','#6c809f','You have reached the roof-level room. Look back: which explanation changed as you explored?']};
 for(const r of house.rooms){const [name,color,entryText]=themes[r.id];Object.assign(r,{name,color,entryText,purpose:entryText,brightness:r.floor===2?70:90});}
 house.ideas=TRAIL_QUESTS.map(q=>({id:'trail-'+q.id,roomId:q.roomId,title:q.title,text:q.lesson+'\n\n'+q.question,cue:q.object,action:'experiment'}));
 for(const [id,roomId,title,text,cue] of [['tower','residence-floor-2','The detective’s final letter','Write one explanation you revised, the evidence that changed it, and a question you still have.','book'],['mirror','art','Two readings of a painting','Describe one painting without interpreting it. Then offer two possible interpretations. Which details support each?','crystal'],['dice','work','A coin that owes you nothing','Toss a real coin ten times and record the sequence. Does an earlier head guarantee a later tail? What assumption are you making about the coin?','sphere'],['clock','learning','The impatient clock','Estimate thirty seconds without a clock, then time another attempt. Compare your estimate with the measurement.','ring'],['map','connections','A map with a missing link','Draw the rooms and their doors as a network. Remove one connection on paper. Which journeys become longer?','book'],['rule','math','Invent a rival rule','Create two rules with the same first three numbers and different fourth numbers. What extra information would distinguish them?','ring']])house.ideas.push({id:'pattern-'+id,roomId,title,text,cue,action:'experiment'});
 return validateHouse(house);
}
