import * as THREE from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {sharedEdge} from './model.js';
import {createJoystick} from './joystick.js';
import {houseBounds,entranceFor,roomAtPoint,reachableIds,walkingRoute,canExploreAt,canOccupy,stepAlongPath,findWalkingPath} from './navigation.js';
import {buildHouse as buildLegacyHouse} from './legacy-scene.js';
import {buildInterior,toggleHomeLight} from './home-interior.js';
import {ideaDisplays} from './idea-display.js';

const toWorld=(x,y)=>new THREE.Vector3(x-10,0,y-8);
export function roomCenter(r){return toWorld(r.x+r.w/2,r.y+r.h/2);}
export function canStandAt(house,walls,x,z){const gx=x+10,gz=z+8,inside=house.rooms.some(r=>gx>=r.x&&gx<=r.x+r.w&&gz>=r.y&&gz<=r.y+r.h);if(!inside)return false;return !walls.some(w=>{const dist=w.axis==='x'?Math.abs(gz-w.fixed):Math.abs(gx-w.fixed),along=w.axis==='x'?gx:gz;return dist<.2&&along>w.lo-.2&&along<w.hi+.2;});}
const mat=(color,roughness=.7,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
const surfaceTextures=new Map();
function surface(type,color,repeatX=1,repeatY=1){
 const material=mat(color,type==='wood'?.62:.88);if(typeof document==='undefined')return material;
 const cacheKey=[type,color,repeatX,repeatY].join(':');if(surfaceTextures.has(cacheKey)){material.color.set('#ffffff');material.map=material.bumpMap=surfaceTextures.get(cacheKey);material.bumpScale=type==='clay'?.028:type==='wood'?.008:.007;return material;}
 const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d');let seed=913;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};ctx.fillStyle=color;ctx.fillRect(0,0,512,512);
 if(type==='wood')for(let row=0;row<8;row++){const y=row*64;ctx.fillStyle=`rgba(${120+random()*50},${83+random()*30},${48+random()*25},.24)`;ctx.fillRect(0,y,512,64);for(let n=0;n<28;n++){ctx.beginPath();ctx.strokeStyle=`rgba(73,47,24,${.025+random()*.075})`;ctx.lineWidth=.4+random();let gy=y+random()*62;ctx.moveTo(0,gy);for(let x=0;x<=512;x+=24)ctx.lineTo(x,gy+Math.sin(x*.028+n)*1.7);ctx.stroke();}ctx.strokeStyle='rgba(74,49,29,.38)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(512,y);ctx.stroke();const joint=(row%3)*170+45;ctx.fillStyle='rgba(75,45,22,.35)';ctx.fillRect(joint,y,1,64);}
 else if(type==='clay'||type==='stone'){const rows=type==='clay'?12:4,cols=type==='clay'?10:5,cw=512/cols,ch=512/rows;for(let row=0;row<rows;row++)for(let col=-1;col<=cols;col++){const shade=random()*35,offset=row%2?cw/2:0;ctx.fillStyle=type==='clay'?`rgb(${135+shade},${74+shade*.7},${52+shade*.5})`:`rgb(${156+shade},${151+shade},${139+shade})`;ctx.fillRect(col*cw+offset+1,row*ch+1,cw-2,ch-2);ctx.strokeStyle='rgba(255,243,215,.09)';ctx.strokeRect(col*cw+offset+2,row*ch+2,cw-4,ch-4);}}
 for(let n=0;n<12000;n++){const alpha=type==='plaster'?.025:.05;ctx.fillStyle=random()>.5?`rgba(255,255,255,${alpha})`:`rgba(45,32,21,${alpha})`;ctx.fillRect(random()*512,random()*512,1+random()*2,1+random()*2);}
 const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(repeatX,repeatY);texture.anisotropy=8;texture.userData.retainedSurface=true;surfaceTextures.set(cacheKey,texture);material.color.set('#ffffff');material.map=texture;material.bumpMap=texture;material.bumpScale=type==='clay'?.028:type==='wood'?.008:.007;material.userData.procedural=true;return material;
}
function box(group,w,h,d,x,y,z,material,data){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;if(data)o.userData=data;group.add(o);return o;}
function sphere(group,r,x,y,z,material){const o=new THREE.Mesh(new THREE.SphereGeometry(r,20,12),material);o.position.set(x,y,z);o.castShadow=true;group.add(o);return o;}
function cylinder(group,r,h,x,y,z,material){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;group.add(o);return o;}
function beam(group,a,b,r,material){const delta=b.clone().sub(a),o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,delta.length(),10),material);o.position.copy(a.clone().add(b).multiplyScalar(.5));o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());o.castShadow=true;group.add(o);return o;}
function label(text,color,scale=3){
 if(typeof document==='undefined')return new THREE.Group();
 const canvas=document.createElement('canvas');canvas.width=768;canvas.height=128;const ctx=canvas.getContext('2d');ctx.font='600 44px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;ctx.fillText(text.length>30?text.slice(0,28)+'…':text,384,64,740);
 const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:true}));sprite.scale.set(scale,scale/6,1);sprite.renderOrder=5;return sprite;
}
const bounds=houseBounds;
const layoutSignature=house=>JSON.stringify({rooms:house.rooms.map(({id,x,y,w,h})=>({id,x,y,w,h})),doors:house.doors});
function outside(house,r,axis,fixed,mid){const epsilon=.02;return !house.rooms.some(other=>other!==r&&(axis==='x'?mid>other.x&&mid<other.x+other.w&&((fixed===r.y&&fixed-epsilon>other.y&&fixed-epsilon<other.y+other.h)||(fixed===r.y+r.h&&fixed+epsilon>other.y&&fixed+epsilon<other.y+other.h)):mid>other.y&&mid<other.y+other.h&&((fixed===r.x&&fixed-epsilon>other.x&&fixed-epsilon<other.x+other.w)||(fixed===r.x+r.w&&fixed+epsilon>other.x&&fixed+epsilon<other.x+other.w))));}
function windowFrame(group,axis,fixed,center,side,width=1.52){
 const frame=surface('wood','#c2ab87'),glass=new THREE.MeshStandardMaterial({color:'#c5d9d9',roughness:.07,metalness:.14,transparent:true,opacity:.1,depthWrite:false,side:THREE.DoubleSide}),cream=mat('#eee6d7'),shutter=surface('wood','#52664e'),x=axis==='x'?center-10:fixed-10+side*.025,z=axis==='z'?center-8:fixed-8+side*.025;
 const orient=(w,h,d,y,m,offset=0)=>box(group,axis==='x'?w:d,h,axis==='z'?w:d,x+(axis==='x'?offset:0),y,z+(axis==='z'?offset:0),m);
 for(const offset of [-width/2,width/2])orient(.075,1.2,.2,1.65,frame,offset);
 for(const y of [1.08,2.22])orient(width+.09,.09,.2,y,cream);
 const pane=orient(width-.07,1.04,.014,1.65,glass);pane.castShadow=false;pane.receiveShadow=false;pane.userData={window:true};
 orient(.045,1.12,.19,1.65,cream);orient(width,.04,.19,1.65,cream);orient(width+.3,.075,.35,1.015,cream);
 for(const direction of [-1,1]){const sx=x+(axis==='x'?direction*(width/2+.23):0),sz=z+(axis==='z'?direction*(width/2+.23):0);box(group,axis==='x'?.31:.11,1.15,axis==='z'?.31:.11,sx,1.65,sz,shutter);for(let n=0;n<7;n++)box(group,axis==='x'?.29:.13,.014,axis==='z'?.29:.13,sx,1.2+n*.14,sz,mat('#687a5d'));}
 const inside=-side*.17,linen=surface('plaster','#f3ebd9');linen.side=THREE.DoubleSide;
 for(const direction of [-1,1]){const cloth=new THREE.PlaneGeometry(.28,1.3,14,4),positions=cloth.attributes.position;for(let n=0;n<positions.count;n++)positions.setZ(n,Math.sin(positions.getX(n)*94)*.035);cloth.computeVertexNormals();const curtain=new THREE.Mesh(cloth,linen);curtain.position.set(x+(axis==='x'?direction*(width/2-.1):inside),1.65,z+(axis==='z'?direction*(width/2-.1):inside));if(axis==='z')curtain.rotation.y=Math.PI/2;curtain.castShadow=true;curtain.userData={curtain:true};group.add(curtain);}
 beam(group,new THREE.Vector3(x+(axis==='x'?-width/2-.18:inside),2.34,z+(axis==='z'?-width/2-.18:inside)),new THREE.Vector3(x+(axis==='x'?width/2+.18:inside),2.34,z+(axis==='z'?width/2+.18:inside)),.021,mat('#76614a'));
}
function plant(group,x,z,size=.5){const terracotta=mat('#a96548'),leaf=mat('#5e8462');cylinder(group,size*.48,size*.55,x,size*.275,z,terracotta);for(let n=0;n<3;n++){const a=n*2.1;sphere(group,size*.48,x+Math.cos(a)*size*.22,size*.7+Math.abs(Math.sin(a))*size*.25,z+Math.sin(a)*size*.22,leaf);}}
function physicalPlaque(group,text,w,x,y,z){
 box(group,w,.18,.045,x,y,z,mat('#81694e'));if(typeof document==='undefined')return;
 const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const ctx=canvas.getContext('2d');ctx.fillStyle='#e8dfcb';ctx.fillRect(0,0,512,96);ctx.fillStyle='#554832';ctx.font='500 34px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,49,480);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const face=new THREE.Mesh(new THREE.PlaneGeometry(w-.045,.145),new THREE.MeshBasicMaterial({map:texture}));face.position.set(x,y,z+.025);group.add(face);
}
function flowerBed(group,x,z,w,d){const soil=mat('#77654e'),leaf=mat('#617451');box(group,w,.08,d,x,-.09,z,soil);for(let n=0;n<Math.max(4,Math.floor(w*d*5));n++){const fx=x-w/2+.16+(n*.47)%(w-.24),fz=z-d/2+.12+(n*.31)%(d-.18);cylinder(group,.024,.24,fx,.12,fz,leaf);const petals=mat(['#e2cd8d','#d39981','#c0c5ad'][n%3]);for(let p=0;p<4;p++){const a=p*Math.PI/2;sphere(group,.06,fx+Math.cos(a)*.05,.26,fz+Math.sin(a)*.05,petals);}}}
function chair(group,x,z,color){const wood=mat('#99704c'),fabric=mat(color);box(group,.55,.13,.55,x,.48,z,fabric);box(group,.55,.6,.1,x,.81,z+.25,fabric);for(const dx of [-.2,.2])for(const dz of [-.2,.2])box(group,.055,.45,.055,x+dx,.225,z+dz,wood);}
function bookshelf(group,x,z,width,color){const wood=mat('#9a7652');box(group,width,1.8,.3,x,.9,z,wood);for(const y of [.4,.9,1.4]){box(group,width+.04,.055,.4,x,y,z+.05,mat('#eddcc1'));for(let n=0;n<Math.floor(width*7);n++)box(group,.08,.28+(n%3)*.04,.21,x-width/2+.1+n*.14,y+.19,z+.18,mat([color,'#d6ad62','#526e69','#e4d4ac'][n%4]));}}
function furniture(group,r,walk){
 const x=r.x-10,z=r.y-8,c=roomCenter(r),wood=mat('#9a7652'),cream=mat('#eadfca'),accent=mat(r.color);
 const rug=box(group,Math.min(r.w-1,3.7),.018,Math.min(r.h-1,2.6),c.x,.015,c.z,mat(new THREE.Color(r.color).lerp(new THREE.Color('#ede2ca'),.55)));rug.userData={roomId:r.id};
 const deskX=x+.85,deskZ=z+r.h-.8;
 box(group,1.25,.11,.72,deskX,.76,deskZ,wood);for(const dx of [-.45,.45])for(const dz of [-.23,.23])box(group,.07,.72,.07,deskX+dx,.36,deskZ+dz,wood);
 chair(group,deskX,deskZ-.67,r.color);for(let n=0;n<3;n++)box(group,.34,.055,.24,deskX+.25,.84+n*.055,deskZ,mat(n===1?r.color:'#e5dcc8'));
 plant(group,x+r.w-.47,z+.48,.44);
 const theme=(r.id+' '+r.name).toLowerCase();
 if(/math|proof|pattern/.test(theme)){
  box(group,2.3,1.3,.11,c.x,1.5,z+.15,wood);box(group,2.15,1.15,.13,c.x,1.5,z+.17,mat('#304a43'));for(const dx of [-.93,.93])box(group,.075,.86,.075,c.x+dx,.43,z+.15,wood);
  const chalk=mat('#eee8d4');beam(group,new THREE.Vector3(c.x-.65,1.13,z+.25),new THREE.Vector3(c.x+.6,1.15,z+.25),.017,chalk);beam(group,new THREE.Vector3(c.x+.6,1.15,z+.25),new THREE.Vector3(c.x-.1,1.92,z+.25),.017,chalk);beam(group,new THREE.Vector3(c.x-.1,1.92,z+.25),new THREE.Vector3(c.x-.65,1.13,z+.25),.017,chalk);
 }else if(/art|image|design/.test(theme)){
  const ex=x+r.w-.9,ez=z+r.h-.85;beam(group,new THREE.Vector3(ex-.45,.04,ez),new THREE.Vector3(ex,1.95,ez+.05),.035,wood);beam(group,new THREE.Vector3(ex+.45,.04,ez),new THREE.Vector3(ex,1.95,ez+.05),.035,wood);box(group,.95,.95,.09,ex,1.3,ez-.04,cream);box(group,.68,.65,.02,ex,1.3,ez-.095,accent);sphere(group,.19,ex-.12,1.36,ez-.11,mat('#e7c26e'));
 }else if(/learning|read|knowledge/.test(theme)){
  bookshelf(group,x+.9,z+.28,Math.min(r.w*.3,1.5),r.color);chair(group,x+r.w-.9,z+r.h-1.1,'#75968b');cylinder(group,.37,.47,x+r.w-1.75,.235,z+r.h-1.1,wood);
 }else if(/question|philos|reflect/.test(theme)){
  const seatX=x+r.w-1.4;chair(group,seatX-.6,z+1.2,r.color);chair(group,seatX+.55,z+1.2,'#d7bd83');cylinder(group,.45,.6,seatX,.3,z+1.7,wood);cylinder(group,.5,.08,seatX,.64,z+1.7,cream);
 }else if(/connect|together/.test(theme)){
  const lounge=new THREE.Group();lounge.position.set(x+r.w-.5,0,z+r.h/2);lounge.rotation.y=-Math.PI/2;group.add(lounge);box(lounge,2.5,.65,.78,0,.46,0,accent);box(lounge,2.5,.62,.2,0,.85,-.34,accent);for(const dx of [-.7,.7])box(lounge,.48,.15,.48,dx,.84,.01,cream);cylinder(lounge,.6,.42,0,.21,.86,wood);
 }else{
  box(group,1.55,1,.13,c.x,1.55,z+.13,wood);box(group,1.42,.88,.15,c.x,1.55,z+.15,cream);for(const dx of [-.65,.65])box(group,.06,1.05,.06,c.x+dx,.525,z+.13,wood);for(let n=0;n<6;n++)box(group,.27,.23,.02,c.x-.5+(n%3)*.5,1.32+Math.floor(n/3)*.4,z+.24,mat(['#cc9f65',r.color,'#a7baa5'][n%3]));
 }
 if(walk){const plaque=label(r.name,'#253c35',Math.min(r.w*.68,3.2));plaque.position.set(c.x,2.4,z+.32);group.add(plaque);}
}
function architecture(group,house,enclosed,obstacles=[]){
 const b=bounds(house),wood=surface('wood','#8a6e4e'),stucco=surface('plaster','#eee4d0'),roofEdge=mat('#795140'),stone=surface('stone','#b8af9a',2,2),entrance=entranceFor(house),doorX=entrance.x,doorZ=entrance.z+.075;
 box(group,b.w+.32,.23,b.d+.32,b.cx,-.16,b.cz,stone);
 box(group,3.6,.1,2.1,doorX,-.012,doorZ+.8,stone);box(group,3.8,.07,.48,doorX,-.07,doorZ+2.05,stone);
 for(let n=0;n<17;n++)box(group,1.64,.045,.58,doorX,-.06,doorZ+2.45+n*.58,stone);
 box(group,Math.min(12,b.w*.65),.035,1.64,doorX+Math.min(6,b.w*.33),-.07,doorZ+6.8,stone);
 plant(group,doorX-1.62,doorZ+1.32,.65);plant(group,doorX+1.62,doorZ+1.32,.65);
 flowerBed(group,b.minX+Math.min(2,b.w*.22),b.maxZ+1.15,Math.min(3.4,b.w*.32),.95);flowerBed(group,b.maxX-Math.min(2,b.w*.22),b.maxZ+1.15,Math.min(3.4,b.w*.32),.95);
 // A usable garden terrace with a bench, a table, and a planted boundary.
 const terraceX=b.minX+1.7,terraceZ=b.maxZ+4;box(group,3.5,.065,2.4,terraceX,-.08,terraceZ,stone);
 const gardenBench=new THREE.Group();group.add(gardenBench);for(const dz of [-.23,.23])box(gardenBench,2.05,.085,.16,terraceX,.48,terraceZ+dz,wood);for(const dx of [-.84,.84])box(gardenBench,.09,.48,.48,terraceX+dx,.24,terraceZ,wood);box(gardenBench,2.05,.55,.08,terraceX,.79,terraceZ-.28,wood);gardenBench.traverse(o=>{o.userData={homeAction:'sit',label:'Sit on the garden bench',anchor:{x:terraceX,z:terraceZ+.95},lookAt:{x:terraceX,z:terraceZ},height:1.13};});cylinder(group,.3,.055,terraceX+1.28,.56,terraceZ,wood);cylinder(group,.06,.54,terraceX+1.28,.27,terraceZ,wood);
 obstacles.push({minX:terraceX-1.05,maxX:terraceX+1.05,minZ:terraceZ-.35,maxZ:terraceZ+.35,label:'Garden bench'},{minX:terraceX+.97,maxX:terraceX+1.59,minZ:terraceZ-.31,maxZ:terraceZ+.31,label:'Garden table'});for(const direction of [-1,1])obstacles.push({minX:doorX+direction*1.62-.32,maxX:doorX+direction*1.62+.32,minZ:doorZ+1,maxZ:doorZ+1.64,label:'Porch planter'});
 const fence=mat('#a8a58c');for(const side of [-1,1]){const fx=side<0?b.minX-3.8:b.maxX+3.8;for(let n=0;n<Math.ceil((b.d+10)/.66);n++)box(group,.095,.87,.15,fx,.26,b.minZ-1.2+n*.66,fence);for(const y of [.14,.47])box(group,.1,.08,b.d+10,fx,y,b.cz+3.5,fence);}for(let n=0;n<Math.ceil((b.w+7)/.66);n++){const fx=b.minX-3.4+n*.66;if(Math.abs(fx-doorX)<1.12)continue;box(group,.14,.85,.09,fx,.26,b.maxZ+7.6,fence);}for(const y of [.14,.47]){box(group,Math.max(.1,doorX-b.minX+2.28),.08,.08,(b.minX-3.4+doorX-1.12)/2,y,b.maxZ+7.6,fence);box(group,Math.max(.1,b.maxX-doorX+2.28),.08,.08,(b.maxX+3.4+doorX+1.12)/2,y,b.maxZ+7.6,fence);}
 for(const fx of [b.minX-3.8,b.maxX+3.8])obstacles.push({minX:fx-.07,maxX:fx+.07,minZ:b.minZ-1.25,maxZ:b.maxZ+8.5,label:'Garden fence'});obstacles.push({minX:b.minX-3.5,maxX:doorX-1.12,minZ:b.maxZ+7.54,maxZ:b.maxZ+7.66,label:'Garden fence'},{minX:doorX+1.12,maxX:b.maxX+3.5,minZ:b.maxZ+7.54,maxZ:b.maxZ+7.66,label:'Garden fence'});
 if(!enclosed)return null;
 const leaf=new THREE.Group();leaf.position.set(doorX-.74,0,doorZ);leaf.rotation.y=0;group.add(leaf);const doorWood=surface('wood','#58614c');box(leaf,1.43,2.13,.095,.715,1.065,0,doorWood);for(const y of [.48,1.14])box(leaf,1.14,.47,.028,.715,y,.063,mat('#67715b'));box(leaf,1.03,.31,.035,.715,1.83,.062,mat('#29382f'));for(const direction of [-1,1])box(leaf,.035,.31,.042,.715+direction*.27,1.83,.085,mat('#d9d3b9'));sphere(leaf,.048,1.2,1.08,.11,mat('#bcaa76',.28,.65));leaf.traverse(o=>{o.userData={door:true,label:'Front door'};});
 for(const dx of [-1.02,1.02]){box(group,.13,.28,.17,doorX+dx,1.86,doorZ+.16,mat('#4a4437'));box(group,.085,.2,.18,doorX+dx,1.86,doorZ+.24,new THREE.MeshStandardMaterial({color:'#dcc191',emissive:'#e6b578',emissiveIntensity:.24}));}
 physicalPlaque(group,'House of Ideas',1.25,doorX-1.37,1.47,doorZ+.105);
 // The entrance has a true gabled porch instead of a flat canopy.
 const porchW=Math.min(3.7,b.w*.7),porchRise=1.02,porchHalf=porchW/2+.18,porchAngle=Math.atan2(porchRise,porchHalf),porchSlope=Math.hypot(porchHalf,porchRise),porchZ=doorZ+.8;
 for(const side of [-1,1]){const slab=box(group,porchSlope,.13,2.35,doorX+side*porchHalf/2,2.57+porchRise/2,porchZ,surface('clay','#a26a50',porchSlope,2));slab.rotation.z=-side*porchAngle;}
 const porchShape=new THREE.Shape();porchShape.moveTo(-porchHalf,2.52);porchShape.lineTo(porchHalf,2.52);porchShape.lineTo(0,2.57+porchRise);porchShape.closePath();const porchFront=new THREE.Mesh(new THREE.ExtrudeGeometry(porchShape,{depth:.08,bevelEnabled:false}),stucco);porchFront.position.set(doorX,0,doorZ+1.92);group.add(porchFront);for(const dx of [-porchW/2+.12,porchW/2-.12])box(group,.13,2.48,.13,doorX+dx,1.24,doorZ+1.68,wood);beam(group,new THREE.Vector3(doorX-porchHalf,2.57,doorZ+2),new THREE.Vector3(doorX,3.59,doorZ+2),.06,wood);beam(group,new THREE.Vector3(doorX+porchHalf,2.57,doorZ+2),new THREE.Vector3(doorX,3.59,doorZ+2),.06,wood);
 const half=b.d/2+.56,rise=Math.min(4,Math.max(2.1,b.d*.32)),angle=Math.atan2(rise,half),length=Math.hypot(half,rise),roofY=2.96;
 for(const side of [-1,1]){const plane=box(group,b.w+1.14,.17,length,b.cx,roofY+rise/2,b.cz+side*half/2,surface('clay','#a36b50',(b.w+1.14)/2,length/2));plane.rotation.x=side*angle;plane.userData={roof:true};box(group,b.w+1.18,.15,.16,b.cx,roofY,b.cz+side*half,wood);cylinder(group,.04,b.w+1.2,b.cx,2.84,b.cz+side*half,mat('#847662')).rotation.z=Math.PI/2;}
 beam(group,new THREE.Vector3(b.minX-.65,roofY+rise,b.cz),new THREE.Vector3(b.maxX+.65,roofY+rise,b.cz),.12,roofEdge);
 const shape=new THREE.Shape();shape.moveTo(-b.d/2,2.79);shape.lineTo(b.d/2,2.79);shape.lineTo(0,roofY+rise-.13);shape.closePath();
 for(const x of [b.minX-.04,b.maxX+.04]){const gable=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.12,bevelEnabled:false}),stucco);gable.rotation.y=Math.PI/2;gable.position.set(x,0,b.cz);gable.castShadow=true;group.add(gable);beam(group,new THREE.Vector3(x,2.87,b.cz-b.d/2),new THREE.Vector3(x,roofY+rise,b.cz),.075,wood);beam(group,new THREE.Vector3(x,2.87,b.cz+b.d/2),new THREE.Vector3(x,roofY+rise,b.cz),.075,wood);const vent=box(group,.13,.72,.8,x,4.05,b.cz,mat('#cbbda0'));for(let n=0;n<5;n++)box(group,.15,.035,.71,x,3.77+n*.13,b.cz,mat('#766b57'));}
 const chimneyX=b.minX+Math.min(2,b.w*.25),chimneyZ=b.cz-b.d*.22,chimneyBase=roofY+rise*(1-Math.abs(chimneyZ-b.cz)/half)-.07;box(group,.63,1.6,.77,chimneyX,chimneyBase+.8,chimneyZ,surface('stone','#a48469',1,2));box(group,.84,.13,.98,chimneyX,chimneyBase+1.64,chimneyZ,stone);box(group,.49,.035,.6,chimneyX,chimneyBase+1.725,chimneyZ,mat('#45443c'));
 return {leaf,x:doorX,z:doorZ,open:false};
}
export function buildHouse(house,walk=false,exterior=false){
 const group=new THREE.Group(),interior=new THREE.Group(),walls=[],floors=[],objects=[],ceilings=[],obstacles=[],interactions=[],entry=entranceFor(house);group.add(interior);interior.visible=!exterior||walk;
 const wallMaterial=surface('plaster','#e9e0cf',3,2),trim=mat('#eee7d9'),skirting=surface('wood','#a8916e'),height=walk||exterior?2.8:.78;
 const edges=house.doors.map(d=>({edge:sharedEdge(house.rooms.find(r=>r.id===d.a),house.rooms.find(r=>r.id===d.b)),...d})),wallKeys=new Set();
 function wall(axis,fixed,lo,hi,room){
  const relevant=edges.filter(d=>(d.a===room.id||d.b===room.id)&&d.edge?.axis===axis&&d.edge.fixed===fixed);
  const holes=relevant.map(d=>{const center=(d.edge.lo+d.edge.hi)/2;return [center-.75,center+.75];});if(axis==='x'&&fixed===entry.z+8&&room.id===entry.roomId)holes.push([entry.x+10-.75,entry.x+10+.75]);holes.sort((a,b)=>a[0]-b[0]);
  const segments=[];let cursor=lo;for(const [a,b] of holes){if(a>cursor)segments.push([cursor,a]);cursor=Math.max(cursor,b);}if(cursor<hi)segments.push([cursor,hi]);
  for(const [a,b] of segments){const key=[axis,fixed,a,b].join(':');if(wallKeys.has(key)||b-a<.02)continue;wallKeys.add(key);const center=(a+b)/2,x=axis==='x'?center-10:fixed-10,z=axis==='z'?center-8:fixed-8;
   const window=(walk||exterior)&&b-a>=2.2&&outside(house,room,axis,fixed,center),windowWidth=Math.min(1.6,b-a-1.1);
   const wallBox=(from,to,bottom,top)=>{const m=(from+to)/2;return box(group,axis==='x'?to-from:.15,top-bottom,axis==='z'?to-from:.15,axis==='x'?m-10:x,(top+bottom)/2,axis==='z'?m-8:z,wallMaterial);};
   if(window){const half=windowWidth/2;wallBox(a,center-half,0,height);wallBox(center+half,b,0,height);wallBox(center-half,center+half,0,1.08);wallBox(center-half,center+half,2.22,height);const side=axis==='x'?(fixed===room.y?-1:1):(fixed===room.x?-1:1);windowFrame(group,axis,fixed,center,side,windowWidth);}else wallBox(a,b,0,height);
   box(group,axis==='x'?b-a+.03:.2,.06,axis==='z'?b-a+.03:.2,x,height+.03,z,trim);box(group,axis==='x'?b-a:.17,.11,axis==='z'?b-a:.17,x,.055,z,skirting);walls.push({axis,fixed,lo:a,hi:b});
  }
  for(const [a,b] of holes){const key='door:'+axis+fixed+':'+a;if(wallKeys.has(key))continue;wallKeys.add(key);const c=(a+b)/2,x=axis==='x'?c-10:fixed-10,z=axis==='z'?c-8:fixed-8;
   if(walk||exterior)box(group,axis==='x'?1.5:.18,.65,axis==='z'?1.5:.18,x,2.475,z,wallMaterial);
   box(group,axis==='x'?1.5:.18,.025,axis==='z'?1.5:.18,x,.04,z,mat('#e0b46c'));
   for(const direction of [-1,1])box(group,axis==='x'?.09:.19,Math.min(height,2.15),axis==='z'?.09:.19,x+(axis==='x'?direction*.75:0),Math.min(height,2.15)/2,z+(axis==='z'?direction*.75:0),trim);
  }
 }
 for(const r of house.rooms){
  const c=roomCenter(r),tile=r.id==='work'||r.id==='learning',floor=box(group,r.w-.03,.12,r.h-.03,c.x,-.055,c.z,surface(tile?'stone':'wood',tile?'#c4bcaa':'#b19a73',r.w/(tile?2.2:3),r.h/(tile?2.2:2)),{roomId:r.id});floors.push(floor);
  wall('x',r.y,r.x,r.x+r.w,r);wall('x',r.y+r.h,r.x,r.x+r.w,r);wall('z',r.x,r.y,r.y+r.h,r);wall('z',r.x+r.w,r.y,r.y+r.h,r);
  if(!walk){const roomLabel=label(r.name.toUpperCase(),'#334d42',Math.min(r.w*.78,4.6));roomLabel.position.set(c.x,.15,r.y-8+.6);roomLabel.userData={roomId:r.id};interior.add(roomLabel);}const domestic=buildInterior(house,r,THREE,{walk});interior.add(domestic.group);obstacles.push(...domestic.obstacles);interactions.push(...domestic.interactions);
  if(walk||exterior){const ceiling=box(group,r.w+.025,.13,r.h+.025,c.x,2.865,c.z,surface('plaster','#f2eadc',2,2));ceiling.userData={ceiling:true,roomId:r.id};ceilings.push(ceiling);cylinder(group,.22,.065,c.x,2.73,c.z,mat('#766a55'));cylinder(group,.17,.045,c.x,2.69,c.z,new THREE.MeshStandardMaterial({color:'#f3e6c5',emissive:'#ffdfac',emissiveIntensity:.8,roughness:.5}));const lamp=new THREE.PointLight('#ffe1b5',5.5,8,2);lamp.position.set(c.x,2.58,c.z);group.add(lamp);}
  const display=ideaDisplays(house,r);for(const cabinet of display.cabinets){const rack=new THREE.Group();rack.position.set(cabinet.x,0,cabinet.z);rack.rotation.y=cabinet.yaw;interior.add(rack);const wood=surface('wood','#9c7d57');box(rack,cabinet.width,2.2,.035,0,1.15,-cabinet.depth/2,wood);for(const dx of [-cabinet.width/2,cabinet.width/2])box(rack,.025,2.24,cabinet.depth,dx,1.14,0,wood);for(const y of [.1,.55,1.17,1.79,2.24])box(rack,cabinet.width,.035,cabinet.depth,0,y,0,wood);obstacles.push({...cabinet,roomId:r.id,label:'Idea display cabinet'});}
  display.slots.forEach(slot=>{
   const {idea,x,z,y,scale}=slot,data={ideaId:idea.id,roomId:r.id};
   const base=slot.pedestal?box(interior,.65,.46,.65,x,.23,z,surface('wood','#b1a080'),data):box(interior,.4,.025,.32,x,slot.shelf+.027,z,mat('#bda785'),data);objects.push(base);if(slot.pedestal)obstacles.push({minX:x-.33,maxX:x+.33,minZ:z-.33,maxZ:z+.33,roomId:r.id,label:idea.title});
   let geometry,rotation=null;if(idea.cue==='crystal')geometry=new THREE.OctahedronGeometry(.43);if(idea.cue==='sphere')geometry=new THREE.SphereGeometry(.34,24,16);if(idea.cue==='ring')geometry=new THREE.TorusGeometry(.32,.095,14,40);if(idea.cue==='book'){geometry=new THREE.BoxGeometry(.54,.13,.4);rotation=[.1,0,.13];}
   const object=new THREE.Mesh(geometry,idea.cue==='book'?mat('#e4dbc5'):mat(r.color,.28,.2));object.position.set(x,y,z);object.scale.setScalar(scale);if(rotation)object.rotation.set(...rotation);object.castShadow=true;object.userData=data;interior.add(object);objects.push(object);
   if(idea.cue==='book'){for(const direction of [-1,1])box(object,.575,.017,.43,0,direction*.078,0,mat(r.color));box(object,.028,.17,.43,-.276,0,0,mat(r.color));for(let n=0;n<4;n++)box(object,.49,.003,.007,.015,-.035+n*.023,.203,mat('#bdb397'));for(let n=0;n<3;n++)box(object,.27-n*.03,.003,.012,.04,.09,-.075+n*.055,mat('#cab886'));}
   if(idea.cue==='sphere'){for(const tilt of [0,Math.PI/2]){const band=new THREE.Mesh(new THREE.TorusGeometry(.343,.01,6,36),mat('#b6a47c',.35,.5));band.rotation.x=tilt;object.add(band);}}
   object.traverse(part=>{part.userData=data;});const title=label(idea.title,'#1d3744',display.dense?.85:Math.min(r.w/3*.93,3.3));title.position.set(x,y+.6*scale,z);title.userData=data;title.visible=!walk;interior.add(title);objects.push(title);
  });
 }
 // Approved additions get separate free floor slots. Existing furnishings are
 // soft obstacles; door openings and previously installed additions stay clear.
 const installedBounds=[],baseBounds=[];interior.updateMatrixWorld(true);interior.traverse(o=>{if(o.isMesh){const b=new THREE.Box3().setFromObject(o);if(b.max.y>.1)baseBounds.push(b);}});
 const overlaps=(a,b,padding=0)=>a.min.x<b.max.x+padding&&a.max.x>b.min.x-padding&&a.min.z<b.max.z+padding&&a.max.z>b.min.z-padding;
 for(const feature of house.resident?.roomFeatures||[]){const r=house.rooms.find(room=>room.id===feature.roomId);if(!r)continue;const x=0,z=0,wood=mat('#93714e'),linen=mat('#e4d7be'),accent=mat(r.color);const installed=new THREE.Group();installed.userData={featureId:feature.id,roomId:r.id};interior.add(installed);
  if(feature.type==='reflection_lamp'){cylinder(installed,.23,.05,x,.03,z,wood);cylinder(installed,.035,1.65,x,.87,z,wood);const shade=new THREE.Mesh(new THREE.CylinderGeometry(.18,.38,.32,20),linen);shade.position.set(x,1.7,z);installed.add(shade);sphere(installed,.1,x,1.6,z,new THREE.MeshStandardMaterial({color:'#f1d69e',emissive:'#eab466',emissiveIntensity:1}));const glow=new THREE.PointLight('#ffd49a',3,3,2);glow.position.set(x,1.45,z);installed.add(glow);}
  if(feature.type==='question_board'){box(installed,1.15,1.03,.11,x,1.38,z,wood);box(installed,1.02,.9,.13,x,1.38,z-.015,linen);for(const dx of [-.44,.44])box(installed,.07,.9,.07,x+dx,.45,z,wood);for(let n=0;n<3;n++)box(installed,.2,.16,.02,x-.3+n*.3,1.36,z-.09,accent);}
  if(feature.type==='experiment_table'){box(installed,1.25,.1,.75,x,.73,z,wood);for(const dx of [-.47,.47])for(const dz of [-.23,.23])box(installed,.06,.68,.06,x+dx,.34,z+dz,wood);sphere(installed,.15,x-.3,.94,z,accent);cylinder(installed,.12,.32,x+.25,.94,z,linen);}
  if(feature.type==='discussion_circle'){chair(installed,x-.4,z, r.color);chair(installed,x+.38,z-.65,'#b69b77');cylinder(installed,.36,.44,x-.25,.22,z-.5,wood);}
  const local=new THREE.Box3().setFromObject(installed),size=local.getSize(new THREE.Vector3()),center=local.getCenter(new THREE.Vector3()),left=r.x-10,top=r.y-8;
  const portals=house.doors.filter(d=>d.a===r.id||d.b===r.id).map(d=>sharedEdge(r,house.rooms.find(room=>room.id===(d.a===r.id?d.b:d.a)))).filter(Boolean);
  if(r.id===entry.roomId)portals.push({axis:'x',fixed:entry.z+8,lo:entry.x+10-.75,hi:entry.x+10+.75,entry:true});
  const doorBounds=portals.map(edge=>{const c=(edge.lo+edge.hi)/2;return edge.axis==='x'?{min:{x:c-10-.8,z:edge.fixed-8-.48},max:{x:c-10+.8,z:edge.fixed-8+.48}}:{min:{x:edge.fixed-10-.48,z:c-8-.8},max:{x:edge.fixed-10+.48,z:c-8+.8}};});
  for(const action of interactions){const data=action.userData||action;if(data.roomId===r.id&&data.anchor)doorBounds.push({min:{x:data.anchor.x-.34,z:data.anchor.z-.34},max:{x:data.anchor.x+.34,z:data.anchor.z+.34}});}
  const base=baseBounds.filter(b=>b.max.x>left&&b.min.x<left+r.w&&b.max.z>top&&b.min.z<top+r.h),preferred={question_board:[.18,.24],reflection_lamp:[.83,.8],experiment_table:[.73,.25],discussion_circle:[.3,.7]}[feature.type]||[.5,.5];
  let placement=null;
  for(let attempt=0;attempt<8&&!placement;attempt++){
   const scale=Math.min(1,Math.min(r.w,r.h)/5)*Math.pow(.87,attempt),hw=size.x*scale/2,hd=size.z*scale/2,minX=left+.16+hw,maxX=left+r.w-.16-hw,minZ=top+.16+hd,maxZ=top+r.h-.16-hd;
   const xs=[minX,maxX,THREE.MathUtils.clamp(left+r.w*preferred[0],minX,maxX)],zs=[minZ,maxZ,THREE.MathUtils.clamp(top+r.h*preferred[1],minZ,maxZ)];for(let px=minX;px<=maxX;px+=.28)xs.push(px);for(let pz=minZ;pz<=maxZ;pz+=.28)zs.push(pz);
   let best=null;for(const px of xs)for(const pz of zs){const b={min:{x:px-hw,z:pz-hd},max:{x:px+hw,z:pz+hd}};if(installedBounds.some(other=>overlaps(b,other,.04))||doorBounds.some(door=>overlaps(b,door)))continue;
    const overlapArea=base.reduce((sum,other)=>sum+(overlaps(b,other)?Math.max(0,Math.min(b.max.x,other.max.x)-Math.max(b.min.x,other.min.x))*Math.max(0,Math.min(b.max.z,other.max.z)-Math.max(b.min.z,other.min.z)):0),0),score=overlapArea*100+Math.hypot(px-(left+r.w*preferred[0]),pz-(top+r.h*preferred[1]));
    if(!best||score<best.score)best={px,pz,scale,score,b};
   }placement=best;
  }
  if(placement){installed.scale.set(placement.scale,Math.max(.8,placement.scale),placement.scale);installed.position.set(placement.px-center.x*placement.scale,0,placement.pz-center.z*placement.scale);installedBounds.push(placement.b);installed.userData.anchor={x:placement.px,z:placement.pz};obstacles.push({minX:placement.b.min.x,maxX:placement.b.max.x,minZ:placement.b.min.z,maxZ:placement.b.max.z,roomId:r.id,label:feature.type});}
  else{interior.remove(installed);}
 }
 const frontDoor=architecture(group,house,exterior||walk,obstacles);return {group,walls,floors,objects,ceilings,obstacles,interactions,frontDoor,entrance:entry};
}

function socratesVisitor(){
 const group=new THREE.Group(),robe=mat('#e6dfc8'),skin=mat('#bb9478'),hair=mat('#d0d0c1'),sandals=mat('#6d5238'),limbs=[];
 const torso=new THREE.Mesh(new THREE.CylinderGeometry(.22,.33,.71,18),robe);torso.position.y=.88;torso.castShadow=true;group.add(torso);
 const sash=box(group,.1,.66,.48,.09,1.02,0,mat('#b79662'));sash.rotation.z=-.18;
 for(const direction of [-1,1]){const arm=new THREE.Group();arm.position.set(direction*.245,1.2,0);group.add(arm);cylinder(arm,.085,.42,0,-.2,0,robe);sphere(arm,.071,0,-.43,-.02,skin);limbs.push({part:arm,sign:direction});
  const leg=new THREE.Group();leg.position.set(direction*.13,.57,0);group.add(leg);cylinder(leg,.072,.38,0,-.18,0,skin);box(leg,.17,.07,.29,0,-.41,-.05,sandals);limbs.push({part:leg,sign:-direction});
 }
 const head=new THREE.Group();head.position.y=1.49;group.add(head);sphere(head,.205,0,0,0,skin);const beard=sphere(head,.15,0,-.11,-.11,hair);beard.scale.set(1,1.23,.7);sphere(head,.14,0,.045,.11,hair);for(const side of [-1,1]){sphere(head,.064,side*.178,.024,0,hair);sphere(head,.025,side*.082,.016,-.181,mat('#d7c4ad'));sphere(head,.01,side*.082,.012,-.201,mat('#2e352d'));const brow=box(head,.061,.015,.026,side*.082,.055,-.186,hair);brow.rotation.z=side*.12;}sphere(head,.047,0,-.016,-.211,skin);
 group.traverse(o=>{o.userData={resident:true};});return {group,limbs,head};
}

export function createScene(container,onPick){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#c9d5dd');scene.fog=new THREE.Fog('#c9d5dd',100,250);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;container.append(renderer.domElement);
 const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','Explore the house. Use W A S D or arrow keys to walk, drag to look, and press E near Socrates to talk.');canvas.style.outlineOffset='-3px';
 const camera=new THREE.PerspectiveCamera(62,1,.045,400),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2-.06;controls.minDistance=5;controls.maxDistance=55;controls.enabled=false;
 scene.add(new THREE.HemisphereLight('#e3edf0','#967f5a',1.35));const sun=new THREE.DirectionalLight('#fff0cf',3.1);sun.position.set(-16,17,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;sun.shadow.normalBias=.025;scene.add(sun);
 box(scene,560,.18,180,0,-.35,0,surface('plaster','#a5af92',140,45));
 const skyCanvas=document.createElement('canvas');skyCanvas.width=1024;skyCanvas.height=512;const skyCtx=skyCanvas.getContext('2d'),gradient=skyCtx.createLinearGradient(0,0,0,512);gradient.addColorStop(0,'#8aa8bd');gradient.addColorStop(.5,'#c4d5dc');gradient.addColorStop(.74,'#e5e8db');gradient.addColorStop(1,'#d5d9c5');skyCtx.fillStyle=gradient;skyCtx.fillRect(0,0,1024,512);for(let n=0;n<12;n++){skyCtx.fillStyle='rgba(249,245,225,.1)';skyCtx.beginPath();skyCtx.ellipse((n*193)%1024,170+(n%3)*23,70+(n%4)*18,11,0,0,Math.PI*2);skyCtx.fill();}const skyTex=new THREE.CanvasTexture(skyCanvas);skyTex.colorSpace=THREE.SRGBColorSpace;const sky=new THREE.Mesh(new THREE.SphereGeometry(370,24,16),new THREE.MeshBasicMaterial({map:skyTex,side:THREE.BackSide,depthWrite:false,fog:false}));scene.add(sky);
 for(const [x,z,size] of [[-14,-9,1.6],[12,-10,1.5],[-15,6,1.45],[14,4,1.35]]){const bark=surface('wood','#74624c');cylinder(scene,.14,2.6,x,1.1,z,bark);for(let n=0;n<5;n++){const a=n*2.4;beam(scene,new THREE.Vector3(x,1.45,z),new THREE.Vector3(x+Math.cos(a)*.85,2.6+(n%2)*.35,z+Math.sin(a)*.85),.05,bark);}for(let n=0;n<14;n++){const a=n*2.4,r=.35+(n%4)*.27;sphere(scene,size*.46,x+Math.cos(a)*r,2.7+(n%3)*.39,z+Math.sin(a)*r,mat(n%2?'#6f835e':'#879772'));}}
 const stick=createJoystick(document.getElementById('joystick'),document.getElementById('joystick-thumb')),resident=socratesVisitor(),visitor=resident.group;scene.add(visitor);
 let house=null,built=null,walk=true,exterior=false,yaw=0,pitch=0,selected=null,last=0,look=null,firstPersonPosition=null,layout=null,edition='inhabited',seated=false,standingPosition=null,seatTarget=null;
 let neighborhoodEntries=[],activeHomeId=null,visitHome=null,neighborhoodMode=false,neighbors=[],neighborhoodRenderKey='',neighborhoodGroup=new THREE.Group();scene.add(neighborhoodGroup);
 let path=[],playerPath=[],targetRoomId=null,residentRoomId=null,residentTalking=false,summoning=false,pause=4,patrolIndex=0,walkingTime=0,visitCallback=null,active=true;
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),held=new Set();ray.camera=camera;
 const dispose=group=>group.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){if(m.map&&!m.map.userData.retainedSurface)m.map.dispose();m.dispose();}}});
 function roomAt(){return house?roomAtPoint(house,camera.position.x,camera.position.z):null;}
 function canNavigate(x,z){return house&&built&&canExploreAt(house,built.walls,x,z)&&canOccupy(built.obstacles||[],x,z,.2);}
 function canStand(x,z){if(!house||!built)return false;if(neighborhoodMode){const b=bounds(house),left=Math.min(b.minX,...neighbors.map(n=>n.minX))-8,right=Math.max(b.maxX,...neighbors.map(n=>n.maxX))+8;if(x<left||x>right||z<b.minZ-8||z>b.maxZ+16)return false;for(const n of neighbors){if(!canOccupy(n.obstacles,x,z,.2)||n.walls.some(w=>{const distance=w.axis==='x'?Math.abs(z+8-w.fixed):Math.abs(x+10-w.fixed),along=w.axis==='x'?x+10:z+8;return distance<.2&&along>w.lo-.2&&along<w.hi+.2;})||Math.abs(z-n.doorZ)<.22&&Math.abs(x-n.doorX)<.86)return false;}if(!canOccupy(built.obstacles||[],x,z,.2))return false;if(built.walls.some(w=>{const distance=w.axis==='x'?Math.abs(z+8-w.fixed):Math.abs(x+10-w.fixed),along=w.axis==='x'?x+10:z+8;return distance<.2&&along>w.lo-.2&&along<w.hi+.2;}))return false;}else if(!canNavigate(x,z))return false;return !(built.frontDoor&&!built.frontDoor.open&&Math.abs(z-built.frontDoor.z)<.2&&Math.abs(x-built.frontDoor.x)<.8);}
 function freePoint(room){const c=roomCenter(room);if(canNavigate(c.x,c.z))return c;for(let radius=.4;radius<Math.min(room.w,room.h)/2;radius+=.35)for(let n=0;n<12;n++){const a=n*Math.PI/6,x=c.x+Math.cos(a)*radius,z=c.z+Math.sin(a)*radius;if(roomAtPoint(house,x,z)===room.id&&canNavigate(x,z))return new THREE.Vector3(x,0,z);}return c;}
 function setDoor(open){if(built?.frontDoor)built.frontDoor.open=Boolean(open);}
 function toggleFrontDoor(){setDoor(!built?.frontDoor?.open);return Boolean(built?.frontDoor?.open);}
 function resetInput(){held.clear();stick.reset();look=null;playerPath=[];seatTarget=null;}
 function faceDirection(){camera.rotation.set(pitch,yaw,0,'YXZ');}
 function spawnOutside(){if(!house)return;neighborhoodMode=false;stand();const e=entranceFor(house),b=bounds(house);camera.position.set(b.maxX+6.2,1.65,e.z+12);const dx=b.cx-camera.position.x,dz=b.cz+1.2-camera.position.z;yaw=Math.atan2(-dx,-dz);pitch=Math.atan2(1.5,Math.hypot(dx,dz));faceDirection();firstPersonPosition=camera.position.clone();resetInput();}
 function overview(){if(!house)return;const b=bounds(house),distance=Math.max(14,b.w*.8,b.d*.9);camera.fov=43;camera.updateProjectionMatrix();camera.position.set(b.cx+distance*.88,exterior?distance*.72:distance,b.cz+distance*1.04);controls.target.set(b.cx,exterior?1.3:0,b.cz);controls.update();resetInput();}
 function rebuild(){if(!house)return;const doorOpen=built?.frontDoor?.open;if(built){scene.remove(built.group);dispose(built.group);}built=(edition==='legacy'?buildLegacyHouse:buildHouse)(house,walk,exterior);if(built.frontDoor&&doorOpen)built.frontDoor.open=true;scene.add(built.group);built.group.updateMatrixWorld(true);if(!canNavigate(visitor.position.x,visitor.position.z)){const c=freePoint(house.rooms.find(r=>r.id===residentRoomId)||house.rooms[0]);visitor.position.copy(c);residentRoomId=roomAtPoint(house,c.x,c.z);path=[];pause=2;}visitor.visible=true;}
 function planVisit(id,target){const room=house.rooms.find(r=>r.id===id);if(!room)return false;const end=target&&canNavigate(target.x,target.z)?target:freePoint(room),next=findWalkingPath(house,built.walls,visitor.position,end,.28,canNavigate);if(!next.length)return false;path=next;targetRoomId=id;pause=0;return true;}
 function enterRoom(id){if(!house)return;const r=house.rooms.find(r=>r.id===id)||house.rooms[0];selected=r.id;if(walk){stand();neighborhoodMode=false;camera.position.copy(freePoint(r));camera.position.y=1.65;yaw=0;pitch=0;faceDirection();firstPersonPosition=camera.position.clone();}else if(!exterior){const target=roomCenter(r),delta=target.clone().sub(controls.target);camera.position.add(delta);controls.target.copy(target);}resetInput();}
 function setWalk(value){value=Boolean(value);if(value===walk)return;if(walk)firstPersonPosition=camera.position.clone();walk=value;exterior=false;controls.enabled=!walk;resetInput();rebuild();if(walk){camera.fov=62;camera.updateProjectionMatrix();if(firstPersonPosition&&canStand(firstPersonPosition.x,firstPersonPosition.z))camera.position.copy(firstPersonPosition);else spawnOutside();faceDirection();}else overview();}
 function setExterior(value){if(value){if(!walk)setWalk(true);spawnOutside();}else if(walk)setWalk(false);}
 function enterHouse(){if(!house)return false;if(!walk)setWalk(true);stand();neighborhoodMode=false;setDoor(true);const e=entranceFor(house);if(roomAt())return true;playerPath=findWalkingPath(house,built.walls,camera.position,{x:e.x,z:e.z-1},.28,canNavigate);return playerPath.length>0;}
 function arriveAtDoor(){if(!house)return false;if(!walk)setWalk(true);stand();neighborhoodMode=false;const e=entranceFor(house);camera.position.set(e.x,1.65,e.z+.6);yaw=0;pitch=0;faceDirection();firstPersonPosition=camera.position.clone();setDoor(true);resetInput();return enterHouse();}
 function stand(){seatTarget=null;if(!seated)return;seated=false;if(!canNavigate(camera.position.x,camera.position.z)&&standingPosition&&canNavigate(standingPosition.x,standingPosition.z))camera.position.copy(standingPosition);camera.position.y=1.65;standingPosition=null;}
 function finishSeating(){if(!seatTarget)return;seated=true;camera.position.y=seatTarget.height;if(seatTarget.lookAt){const dx=seatTarget.lookAt.x-camera.position.x,dz=seatTarget.lookAt.z-camera.position.z;yaw=Math.atan2(-dx,-dz);pitch=-.08;faceDirection();}seatTarget=null;firstPersonPosition=camera.position.clone();}
 function seatAt(data){if(!house||!data?.anchor||!canNavigate(data.anchor.x,data.anchor.z))return false;if(!walk)setWalk(true);stand();const reach=findWalkingPath(house,built.walls,camera.position,data.anchor,.28,canNavigate);if(!reach.length&&Math.hypot(camera.position.x-data.anchor.x,camera.position.z-data.anchor.z)>.15)return false;standingPosition=camera.position.clone();seatTarget={...data,height:Number.isFinite(data.height)?data.height:1.1};playerPath=reach;if(!reach.length)finishSeating();return true;}
 function renderNeighborhood(){if(!house)return;const front=entranceFor(house).z,all=neighborhoodEntries.filter(h=>h.house),activeIndex=Math.max(0,all.findIndex(h=>h.id===activeHomeId)),start=Math.min(Math.max(0,activeIndex-3),Math.max(0,all.length-8)),visible=all.slice(start,start+8).filter(h=>h.id!==activeHomeId),lotWidth=Math.max(27,...all.map(h=>bounds(h.house).w+9)),key=JSON.stringify([activeHomeId,front,lotWidth,...visible.map(h=>[h.id,h.title,h.edition,h.house.rooms,h.house.doors])]);if(key===neighborhoodRenderKey)return;neighborhoodRenderKey=key;scene.remove(neighborhoodGroup);dispose(neighborhoodGroup);neighborhoodGroup=new THREE.Group();scene.add(neighborhoodGroup);neighbors=[];for(const home of visible){const offset=(all.indexOf(home)-activeIndex)*lotWidth,archived=(home.edition==='legacy'?buildLegacyHouse:buildHouse)(home.house,false,true),entry=entranceFor(home.house),dz=front-entry.z;archived.group.position.set(offset,0,dz);archived.group.traverse(o=>{if(o.isLight)o.visible=false;});neighborhoodGroup.add(archived.group);const visitData={homeId:home.id,label:'Visit '+(home.title||'earlier home')};box(archived.group,1.44,2.1,.095,entry.x,1.05,entry.z+.23,surface('wood','#526049'),visitData);physicalPlaque(archived.group,(home.title||'Earlier home').slice(0,28),1.5,entry.x+1.3,1.55,entry.z+.15);const walls=archived.walls.map(w=>w.axis==='x'?{...w,fixed:w.fixed+dz,lo:w.lo+offset,hi:w.hi+offset}:{...w,fixed:w.fixed+offset,lo:w.lo+dz,hi:w.hi+dz});const obstacles=(archived.obstacles||[]).map(o=>({...o,minX:o.minX+offset,maxX:o.maxX+offset,minZ:o.minZ+dz,maxZ:o.maxZ+dz}));neighbors.push({id:home.id,walls,obstacles,minX:bounds(home.house).minX+offset,maxX:bounds(home.house).maxX+offset,doorX:entry.x+offset,doorZ:front+.23});}
  if(neighbors.length){const left=Math.min(bounds(house).minX,...neighbors.map(n=>n.minX))-5,right=Math.max(bounds(house).maxX,...neighbors.map(n=>n.maxX))+5;box(neighborhoodGroup,right-left,.045,3.3,(left+right)/2,-.12,front+11,surface('stone','#b6afa0',(right-left)/2,1));for(const n of neighbors)box(neighborhoodGroup,1.55,.035,7.7,n.doorX,-.08,front+6.4,surface('stone','#c3bca9',1,4));}
  neighborhoodGroup.updateMatrixWorld(true);
 }
 function setNeighborhood(entries,id,onVisit){neighborhoodEntries=Array.isArray(entries)?entries:entries?.homes||[];activeHomeId=id||entries?.activeId||null;visitHome=typeof onVisit==='function'?onVisit:null;renderNeighborhood();}
 function showNeighborhood(){if(!house)return;if(!walk)setWalk(true);stand();neighborhoodMode=true;setDoor(true);const e=entranceFor(house);camera.position.set(e.x,1.65,e.z+10.4);yaw=neighbors.some(n=>n.doorX<e.x)?Math.PI/2:neighbors.length?-Math.PI/2:0;pitch=0;faceDirection();resetInput();}
 function setEdition(value){const next=value==='legacy'?'legacy':'inhabited';if(next===edition)return;edition=next;neighborhoodMode=false;rebuild();spawnOutside();renderNeighborhood();}
 function targetData(object){let node=object;while(node){const data=node.userData;if(data?.homeId||data?.homeAction||data?.ideaId||data?.door||data?.resident)return data;node=node.parent;}return null;}
 function visibleObject(object){for(let node=object;node;node=node.parent)if(!node.visible)return false;return true;}
 function glassObject(object){const materials=Array.isArray(object.material)?object.material:[object.material];return materials.length&&materials.every(m=>m?.transparent&&m.opacity<.2);}
 function focusedTarget(){if(!walk||!built)return null;scene.updateMatrixWorld(true);ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=ray.intersectObjects([visitor,built.group,neighborhoodGroup],true);for(const hit of hits){if(hit.distance>2.6)return null;if(!visibleObject(hit.object)||glassObject(hit.object))continue;const data=targetData(hit.object);if(data?.ideaId){const idea=house.ideas.find(i=>i.id===data.ideaId);return {...data,label:(idea?.title||'Idea object')+' · inspect'};}if(data?.door)return {...data,label:built.frontDoor?.open?'Close front door':'Open front door'};if(data?.resident)return residentState().near?{resident:true,label:'Talk with Socrates'}:null;return data||null;}return null;}
 function useTarget(data){if(!data)return false;if(data.door){toggleFrontDoor();return true;}if(data.homeAction==='light'){toggleHomeLight(built.group,data.homeLightId);return true;}if(data.homeId){if(visitHome)visitHome(data.homeId);else onPick(data);return true;}if(data.resident){talk();return true;}onPick(data);return true;}
 function lineOfSight(){if(!built)return false;scene.updateMatrixWorld(true);const from=camera.position.clone(),to=visitor.position.clone().add(new THREE.Vector3(0,1.1,0)),delta=to.sub(from),distance=delta.length();ray.set(from,delta.normalize());const hits=ray.intersectObjects(built.group.children,true).filter(h=>visibleObject(h.object)&&h.object.geometry&&!glassObject(h.object));return !hits.length||hits[0].distance>distance-.18;}
 function residentState(){const distance=house?Math.hypot(camera.position.x-visitor.position.x,camera.position.z-visitor.position.z):Infinity;return {roomId:residentRoomId,targetRoomId,activity:residentTalking?'talking':path.length&&pause<=0?'walking':'observing',near:Boolean(walk&&distance<=3.2&&lineOfSight()),distance:Number.isFinite(distance)?distance:null,talking:residentTalking,summoning,position:{x:visitor.position.x,z:visitor.position.z}};}
 function talk(){if(residentState().near)onPick({resident:true,roomId:residentRoomId});}
 function summonResident(){if(!house)return false;residentTalking=false;setDoor(true);const playerRoom=roomAt(),e=entranceFor(house);if(playerRoom){const r=house.rooms.find(r=>r.id===playerRoom),target={x:THREE.MathUtils.clamp(camera.position.x-Math.sin(yaw)*1.2,r.x-10+.5,r.x+r.w-10-.5),z:THREE.MathUtils.clamp(camera.position.z-Math.cos(yaw)*1.2,r.y-8+.5,r.y+r.h-8-.5)};if(!canNavigate(target.x,target.z)){const c=freePoint(r);target.x=c.x;target.z=c.z;}summoning=planVisit(playerRoom,target);}else{let target={x:camera.position.x-Math.sin(yaw)*1.8,z:camera.position.z-Math.cos(yaw)*1.8};if(!canNavigate(target.x,target.z))target={x:e.x,z:e.z+1.4};path=findWalkingPath(house,built.walls,visitor.position,target,.28,canNavigate);targetRoomId=null;pause=0;summoning=path.length>0;}return summoning;}
 const observer=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);});observer.observe(container);
 const keys={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
 canvas.addEventListener('keydown',e=>{if(keys[e.code]){e.preventDefault();held.add(keys[e.code]);}if(e.code==='KeyE'&&!e.repeat){e.preventDefault();if(!useTarget(focusedTarget()))talk();}});
 canvas.addEventListener('keyup',e=>{if(keys[e.code]){e.preventDefault();held.delete(keys[e.code]);}});canvas.addEventListener('blur',resetInput);window.addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(!active)resetInput();});
 canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;canvas.focus({preventScroll:true});look={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};if(walk)canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(!look||look.id!==e.pointerId)return;const dx=e.clientX-look.lastX,dy=e.clientY-look.lastY;if(Math.hypot(e.clientX-look.x,e.clientY-look.y)>6)look.moved=true;if(walk){yaw-=dx*.005;pitch=THREE.MathUtils.clamp(pitch-dy*.004,-1.12,1.12);faceDirection();}look.lastX=e.clientX;look.lastY=e.clientY;});
 canvas.addEventListener('pointerup',e=>{if(!look||look.id!==e.pointerId)return;const click=!look.moved;look=null;if(!click||!built)return;const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);scene.updateMatrixWorld(true);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects([visitor,built.group,neighborhoodGroup],true);for(const hit of hits){if(!visibleObject(hit.object)||glassObject(hit.object))continue;if(walk&&hit.distance>2.6)break;const data=targetData(hit.object);if(data){if(data.resident){if(!walk||residentState().near)onPick({resident:true,roomId:residentRoomId});}else useTarget(data);break;}if(!walk&&hit.object.userData.roomId){onPick(hit.object.userData);break;}if(hit.object.geometry)break;}});
 canvas.addEventListener('pointercancel',()=>{look=null;});
 function moveResident(dt){if(!house)return;residentRoomId=roomAtPoint(house,visitor.position.x,visitor.position.z);const dx=camera.position.x-visitor.position.x,dz=camera.position.z-visitor.position.z,near=walk&&Math.hypot(dx,dz)<2.25&&lineOfSight();let moved=0;
  if(residentTalking||(near&&!summoning)){visitor.rotation.y=Math.atan2(-dx,-dz);resident.head.rotation.y=0;}
  else if(path.length){if(pause>0)pause-=dt;else{const step=stepAlongPath(visitor.position,path,dt*.9,canStand);moved=step.moved;if(step.heading!==null)visitor.rotation.y=step.heading;if(step.finished){summoning=false;residentRoomId=roomAtPoint(house,visitor.position.x,visitor.position.z);pause=5;targetRoomId=null;if(residentRoomId&&visitCallback)visitCallback({roomId:residentRoomId,position:{x:visitor.position.x,z:visitor.position.z}});}}}
  else{pause-=dt;if(pause<=0){const start=residentRoomId||entranceFor(house).roomId,reachable=reachableIds(house,start),available=house.rooms.filter(r=>reachable.includes(r.id)).map(r=>r.id);patrolIndex=(patrolIndex+1)%available.length;let next=available[patrolIndex];if(next===start&&available.length>1){patrolIndex=(patrolIndex+1)%available.length;next=available[patrolIndex];}if(!planVisit(next)){pause=5;}}}
  if(moved)walkingTime+=dt*6;for(const limb of resident.limbs)limb.part.rotation.x=moved?Math.sin(walkingTime)*.31*limb.sign:limb.part.rotation.x*.82;visitor.position.y=moved?Math.abs(Math.sin(walkingTime))*.017:0;
 }
 function animate(now){const dt=Math.min((now-last)/1000||0,.05);last=now;if(active&&house){let x=stick.state.x+Number(held.has('right'))-Number(held.has('left')),y=stick.state.y+Number(held.has('up'))-Number(held.has('down')),length=Math.max(1,Math.hypot(x,y));x/=length;y/=length;
  const door=built.frontDoor;if(door){const approaching=(x||y||playerPath.length)&&Math.hypot(camera.position.x-door.x,camera.position.z-door.z)<1.5,visitorApproaching=path.length&&pause<=0&&Math.hypot(visitor.position.x-door.x,visitor.position.z-door.z)<1.5;if(approaching||visitorApproaching)setDoor(true);const target=door.open?-Math.PI*.47:0;door.leaf.rotation.y+=(target-door.leaf.rotation.y)*Math.min(1,dt*7);}
  if(x||y){playerPath=[];stand();if(walk){const forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),delta=forward.multiplyScalar(y*dt*2.7).add(right.multiplyScalar(x*dt*2.7)),nx=camera.position.x+delta.x,nz=camera.position.z+delta.z;if(canStand(nx,camera.position.z))camera.position.x=nx;if(canStand(camera.position.x,nz))camera.position.z=nz;firstPersonPosition=camera.position.clone();}else{const f=controls.target.clone().sub(camera.position);f.y=0;f.normalize();const r=new THREE.Vector3(-f.z,0,f.x),delta=f.multiplyScalar(y*dt*8).add(r.multiplyScalar(x*dt*8));camera.position.add(delta);controls.target.add(delta);}}
  else if(walk&&playerPath.length){const step=stepAlongPath(camera.position,playerPath,dt*2.1,canStand);if(step.heading!==null){const angle=Math.atan2(Math.sin(step.heading-yaw),Math.cos(step.heading-yaw));yaw+=angle*Math.min(1,dt*6);faceDirection();}if(step.finished)finishSeating();firstPersonPosition=camera.position.clone();}
  moveResident(dt);
 }if(!walk)controls.update();renderer.render(scene,camera);requestAnimationFrame(animate);}
 requestAnimationFrame(animate);
 return {load(next,options={}){const first=!house,newLayout=layoutSignature(next);if(options.edition)edition=options.edition==='legacy'?'legacy':'inhabited';if(layout&&layout!==newLayout){path=[];targetRoomId=null;pause=2;stand();resetInput();}layout=newLayout;house=next;selected=house.rooms.some(r=>r.id===selected)?selected:entranceFor(house).roomId;rebuild();if(first){const e=entranceFor(house),room=house.rooms.find(r=>r.id===e.roomId),c=freePoint(room);visitor.position.set(c.x,0,c.z);residentRoomId=e.roomId;path=[];targetRoomId=null;pause=4;if(walk)spawnOutside();else overview();}else if(walk&&!canStand(camera.position.x,camera.position.z))spawnOutside();if(path.some(p=>!canNavigate(p.x,p.z))){path=[];pause=2;}renderNeighborhood();},select:enterRoom,setWalk,setExterior,setEdition,setNeighborhood,showNeighborhood,focusedTarget,seatAt,stand,toggleFrontDoor,setSocrates(){visitor.visible=true;},setResidentTalking(value){residentTalking=Boolean(value);if(residentTalking)resetInput();},residentState,summonResident,onResidentVisit(callback){visitCallback=typeof callback==='function'?callback:null;},setResidentObserver(callback){visitCallback=typeof callback==='function'?callback:null;},restoreResidentState(state){if(!state?.position||!canNavigate(state.position.x,state.position.z))return false;visitor.position.set(state.position.x,0,state.position.z);residentRoomId=roomAtPoint(house,visitor.position.x,visitor.position.z);path=[];pause=3;return true;},enterHouse,arriveAtDoor,startOutside(){if(!walk)setWalk(true);spawnOutside();},enterOutside(){if(!walk)setWalk(true);spawnOutside();},reset(){if(walk)spawnOutside();else overview();},get walking(){return walk;},get exterior(){return walk&&!roomAt();},roomAt,playerState(){return {roomId:roomAt(),position:{x:camera.position.x,z:camera.position.z},yaw,pitch,outside:!roomAt(),entering:playerPath.length>0,seated,neighborhood:neighborhoodMode};}};
}
