import {ARTISTS} from './artist-catalog.js';
import {DALI_OBJECTS} from './dali-data.js';
import {MATH_FLOORS,MATH_CONCEPTS} from './math-city-data.js';

export function worldInventory(house,scene,network={}){
 const out=[];const resident=scene?.residentState?.(),residentRoom=house.rooms.find(r=>r.id===resident?.roomId)||house.rooms[0];if(residentRoom)out.push({id:'resident:socrates',city:'home',roomId:residentRoom.id,resident:true,floor:residentRoom.floor||0,title:'Socrates',kind:'Resident',location:residentRoom.name+' · personal home',description:'Your interpretive philosophical companion. Meet him in the home to discuss a room or an idea.'});
 for(const room of house.rooms){const location=room.name+' · '+(room.floor?'Floor '+(room.floor+1):'Ground floor'),base={city:'home',roomId:room.id,floor:room.floor||0,x:room.x+room.w/2-10,z:room.y+room.h/2-8,location};out.push({...base,id:'room:'+room.id,title:room.name,kind:'Room',description:room.purpose||'A room in your current home.'});for(const [i,item] of (scene?.roomInventory?.(room.id)||[]).entries())out.push({...base,...item,id:'room:'+room.id+':'+i,title:item.label||'Room object',kind:'Object',description:'Located in '+location+'. Choose Visit, then inspect it in the room.'});}
 ARTISTS.forEach((artist,i)=>{const x=artist.id==='dali'?0:(i%5-2)*10,z=artist.id==='dali'?-25:i<5?-9:9,base={city:'artists',artistId:artist.id,x,z,location:artist.name+'’s house · '+(artist.id==='dali'?'Surrealist courtyard':'Artists’ avenue')};out.push({...base,id:'artist:'+artist.id,title:artist.name+'’s house',kind:'Residence',description:artist.description});out.push({...base,id:'resident:'+artist.id,title:artist.name,kind:'Resident',description:'Interpretive artist simulation. Meet the resident in their own house.'});if(artist.id!=='dali')for(const [id,title] of [['bench','Gallery bench'],['table','Artist study table']])out.push({...base,id:'gallery:'+artist.id+':'+id,title:artist.name+' · '+title,kind:'Gallery object',workId:artist.works[0].id,description:'A study place in this gallery. Inspect the artist’s work, try its practice and save a reflection.'});artist.works.forEach(work=>out.push({...base,id:'work:'+artist.id+':'+work.id,title:work.title,workId:work.id,kind:'Painting',description:work.description}));});
 for(const object of DALI_OBJECTS)out.push({id:'dali:'+object.id,city:'artists',artistId:'dali',daliObjectId:object.id,title:object.title,kind:'Activity object',x:object.x,z:object.z-25,location:'Dalí’s dream residence · '+object.action,description:object.text});
 for(const [i,edition] of (network.artistHomes?.editions||[]).entries())out.push({id:'edition:'+edition.id,city:'artists',artistId:edition.artistId,artistEditionId:edition.id,title:ARTISTS.find(a=>a.id===edition.artistId)?.name+' · home '+edition.number,kind:'Preserved edition',x:(i%5-2)*10,z:23+Math.floor(i/5)*14,location:'Study gardens · lot '+(i+1),description:edition.reason});
 for(const floor of MATH_FLOORS){out.push({id:'math:'+floor.id,city:'mathematics',floor:floor.index,title:floor.name,kind:'Floor',location:'Mathematics Institute · '+(floor.index===0?'Ground floor':'Floor '+(floor.index+1)),description:floor.description});for(const concept of MATH_CONCEPTS.filter(c=>c.floor===floor.index))out.push({id:'concept:'+concept.id,city:'mathematics',floor:floor.index,conceptId:concept.id,title:concept.title,kind:'Learning station',location:floor.name+' · Floor '+(floor.index+1),description:concept.summary});}
 out.push({id:'makers',city:'makers',title:'Makers’ City',kind:'City',location:'Makers’ City · arrival square',description:'Travel to workshops and explore your collected city objects.'});
 for(const placement of network.placements||[]){const cargo=(network.cargo||[]).find(c=>c.id===placement.cargoId);if(cargo)out.push({id:'cargo:'+placement.id,city:placement.cityId,cargoId:cargo.id,title:cargo.title,kind:'Collection object',location:placement.cityId+' · '+placement.anchorId,description:cargo.text});}
 return out;
}

export function initWorldGuide({document,window,scene,getHouse,getNetwork,visitRoom,inspectWork,inspectConcept,inspectHomeObject,meetResident,saveObservation,discussArtist,notify}){
 const dialog=document.getElementById('world-guide-dialog'),open=document.getElementById('world-guide-open');if(!dialog||!open)return null;
 const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 let selected=null,inventory=[];const drafts=new Map();
 const header=node('div');header.className='dialog-head';const heading=node('h2','World guide'),close=node('button','Close');close.type='button';close.onclick=()=>dialog.close();header.append(heading,close);
 const lead=node('p','Find a place, its resident or an object. The map shows house locations; room objects are grouped in their room.');
 const controls=node('div');controls.className='world-guide-filters';const search=node('input');search.type='search';search.placeholder='Find a book, painting, room or resident';search.setAttribute('aria-label','Search world objects');
 const city=node('select');city.setAttribute('aria-label','Choose city');for(const [id,label] of [['home','My home'],['artists','Artists’ City'],['mathematics','Mathematics City'],['makers','Makers’ City']]){const o=node('option',label);o.value=id;city.append(o);}const level=node('select');level.setAttribute('aria-label','Choose floor');controls.append(search,city,level);
 const layout=node('div');layout.className='world-guide-layout';const map=node('div');map.className='world-guide-map';const list=node('div');list.className='world-guide-list';const detail=node('section');detail.className='world-guide-detail';detail.setAttribute('aria-live','polite');layout.append(map,list);const count=node('p');count.setAttribute('role','status');
 const tools=node('div');tools.className='world-guide-tools';for(const [id,label] of [['residence-open','Home & Socrates'],['residence-map-open','Assign rooms & ideas'],['city-travel-open','Travel & collection'],['art-city-open','Artist galleries'],['math-city-open','Mathematics & Atlas'],['neighborhood-toggle','Earlier homes'],['conversations-open','Conversations'],['design-open','Design workshop'],['journal-toggle','Journal']]){const b=node('button',label);b.type='button';b.onclick=()=>{dialog.close();document.getElementById(id)?.click();};tools.append(b);}
 dialog.append(header,lead,controls,count,layout,detail,node('h3','House tools'),tools);
 const button=(text,fn)=>{const b=node('button',text);b.type='button';b.onclick=fn;return b;};
 function showDetail(item){selected=item.id;detail.replaceChildren(node('small',item.kind+' · '+item.location),node('h3',item.title),node('p',item.description||''),button('Visit this place',()=>go(item)));if(item.workId)detail.append(button('Inspect painting & museum source',()=>{dialog.close();inspectWork(item.artistId,item.workId);}));if(item.daliObjectId){const object=DALI_OBJECTS.find(o=>o.id===item.daliObjectId);detail.append(node('h4',object.action),node('p',object.text),node('small','An original learning object in an imagined Dalí residence.'));if(object.id==='dream-chair')detail.append(button('Sit beside the dream chair',()=>{dialog.close();scene?.enterArtistHouse?.('dali');scene?.seatAt?.({anchor:{x:-3,z:-23},lookAt:{x:0,y:1.8,z:-26},height:1.1});}));detail.append(button('Discuss this object with Dalí',()=>{dialog.close();scene?.enterArtistHouse?.('dali');discussArtist?.('dali',object.title+'. '+object.text);}));const label=node('label','Your observation'),answer=node('textarea');answer.rows=3;answer.maxLength=1500;answer.value=drafts.get(object.id)||'';answer.oninput=()=>drafts.set(object.id,answer.value);label.append(answer);const feedback=node('p');feedback.setAttribute('role','status');detail.append(label,button('Save in city journal',async()=>{if(!answer.value.trim()){feedback.textContent='Write an observation first.';return;}try{await saveObservation?.(object.title,answer.value);drafts.delete(object.id);answer.value='';feedback.textContent='Observation saved in the Artists’ City journal.';}catch(e){feedback.textContent=e.message;}}),feedback);}if(item.conceptId)detail.append(button('Explore this idea',()=>{dialog.close();inspectConcept(item.conceptId);}));if(item.roomId&&item.kind==='Object')detail.append(button('Use this object',()=>{dialog.close();scene?.leaveArtCity?.();visitRoom(item.roomId);inspectHomeObject(item);}));}
 async function go(item){try{dialog.close();if(item.resident){await meetResident?.();}else if(item.artistId)scene?.enterArtistHouse?.(item.artistId,item.artistEditionId);else if(item.roomId){scene?.leaveArtCity?.();visitRoom(item.roomId);}else if(item.city==='mathematics'){scene?.travelToCity?.('mathematics');scene?.visitMathFloor?.(item.floor||0);}else scene?.travelToCity?.(item.city);}catch(e){notify(e.message,true);}}
 function renderMap(items){map.replaceChildren();if(city.value==='mathematics'){map.append(node('p','Vertical map · select a floor'));for(const floor of [...MATH_FLOORS].reverse())map.append(button((floor.index+1)+' · '+floor.name,()=>{level.value=String(floor.index);render();showDetail(inventory.find(i=>i.id==='math:'+floor.id));}));return;}if(city.value==='makers'){map.append(node('p','Makers’ City · use Travel & collection for workshops and landmarks.'));return;}
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',city.value==='artists'?'-30 -36 60 '+Math.max(57,...items.map(i=>(i.z||0)+42)):'-12 -10 26 22');svg.setAttribute('role','group');svg.setAttribute('aria-label',city.value==='artists'?'Artists’ City house locations':'Current home room map');
 const rect=(x,z,w,h,color)=>{const r=document.createElementNS(ns,'rect');for(const [k,v] of Object.entries({x,y:z,width:w,height:h,fill:color,stroke:'#e9ddc2','stroke-width':'.12'}))r.setAttribute(k,String(v));svg.append(r);return r;};
 if(city.value==='home')for(const r of getHouse().rooms.filter(r=>(r.floor||0)===Number(level.value)))rect(r.x-10,r.y-8,r.w,r.h,'#63756a');
 else{rect(-26,-2,52,4,'#ad9675');for(const item of items.filter(i=>i.kind==='Residence'||i.kind==='Preserved edition'))rect(item.x-(item.artistId==='dali'&&!item.artistEditionId?6:3.5),item.z-(item.artistId==='dali'&&!item.artistEditionId?5:3),item.artistId==='dali'&&!item.artistEditionId?12:7,item.artistId==='dali'&&!item.artistEditionId?10:6,item.artistId==='dali'?'#bb9361':'#647c72');}
 const markers=city.value==='home'?items.filter(i=>i.kind==='Room'):items.filter(i=>i.kind==='Residence'||i.kind==='Preserved edition'||i.daliObjectId);
 for(const item of markers){const g=document.createElementNS(ns,'g'),c=document.createElementNS(ns,'circle'),title=document.createElementNS(ns,'title');c.setAttribute('cx',item.x);c.setAttribute('cy',item.z);c.setAttribute('r',item.daliObjectId?'.32':'.65');c.setAttribute('fill',item.id===selected?'#f0ca78':'#fcf0cc');title.textContent=item.title;g.append(c,title);g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',item.title);g.onclick=()=>showDetail(item);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showDetail(item);}};svg.append(g);}map.append(svg,node('small',city.value==='artists'?'Artists’ avenue is at the centre. Dalí’s courtyard is above; preserved study editions are below.':'Select a room marker, then choose a room object from the list.'));
 }
 function render(){const query=search.value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),items=inventory.filter(i=>i.city===city.value&&(city.value!=='home'&&city.value!=='mathematics'||i.floor===Number(level.value))),matches=items.filter(i=>[i.title,i.location,i.kind,i.description].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query));count.textContent=matches.length+' places and objects found';list.replaceChildren(...matches.map(item=>{const b=button(item.title+' · '+item.kind,()=>showDetail(item));b.append(node('small',item.location));return b;}));if(!matches.length)list.append(node('p','No matches. Try another name or city.'));renderMap(items);}
 function floors(){level.replaceChildren();const n=city.value==='mathematics'?8:Math.max(1,...getHouse().rooms.map(r=>(r.floor||0)+1));for(let i=0;i<n;i++){const o=node('option',i===0?'Ground floor':'Floor '+(i+1));o.value=String(i);level.append(o);}level.hidden=!['home','mathematics'].includes(city.value);}
 function show(){inventory=worldInventory(getHouse(),scene,getNetwork?.());city.value=scene?.playerState?.().cityId||'home';search.value='';floors();level.value=String(scene?.playerState?.().floor||0);detail.replaceChildren();render();if(!dialog.open)dialog.showModal();search.focus();}
 open.onclick=show;search.oninput=render;city.onchange=()=>{floors();detail.replaceChildren();render();};level.onchange=render;
 window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='m'&&!e.ctrlKey&&!e.metaKey&&!['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();show();}});
 return {show,inspectDali(id){show();city.value='artists';floors();render();const item=inventory.find(i=>i.daliObjectId===id);if(item)showDetail(item);}};
}
